### ISSUE TITLE
Problem with GSL when building O2

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#138]
When building GSL for O2 I get : 

> /home/flpprotodev/alice/sw/BUILD/49db3fe4c312a3f2fefa8fe09f95f98e85f981ae/GSL/missing: line 81: makeinfo: command not found
> WARNING: 'makeinfo' is missing on your system.
>          You should only need it if you modified a '.texi' file, or
>          any other file indirectly affecting the aspect of the manual.
>          You might want to install the Texinfo package:
>          <http://www.gnu.org/software/texinfo/>
>          The spurious makeinfo call might also be the consequence of
>          using a buggy 'make' (AIX, DU, IRIX), in which case you might
>          want to install GNU make:
>          <http://www.gnu.org/software/make/>
> make[2]: *** [gsl-ref.info] Error 127
> make[2]: Leaving directory `/home/flpprotodev/alice/sw/BUILD/49db3fe4c312a3f2fefa8fe09f95f98e85f981ae/GSL/doc'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/home/flpprotodev/alice/sw/BUILD/49db3fe4c312a3f2fefa8fe09f95f98e85f981ae/GSL'
> make: *** [all] Error 2

Either install makeinfo with alibuild or (preferably) disable documentation for GSL.

**Comment by ktf** [comment]
Yes, indeed. The main problem is that texinfo is complicated to build and dropping documentation is not easy as well. Will try to look into this ASAP.

**Comment by ktf** [comment]
Actually dropping the documentation is almost easy. Can you please confirm?

**Comment by Barthelemy** [comment]
Sure, go ahead !

**Comment by ktf** [comment]
Closing this as it should be fixed. Reopen if not the case.
