### ISSUE TITLE
alibuild fails on Mac if sha1sum is not installed

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#144]
When sha1sum is not installed on Mac, aliBuild fails with this error 

> Unable to detect source code changes.

Maybe you could detect it and provide a more insightful message.

**Comment by ktf** [comment]
Actually I think I should simply use `shasum` in place of `sha1sum`, which exists on mac.

**Comment by Barthelemy** [comment]
Agreed.

**Comment by ktf** [comment]
Closing this as I think it's fixed in `next` branch and will go in `master` soon. Reopen if not the case.
