### ISSUE TITLE
alienv enter should not continue if one of the dependencies exits

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#176]

**Comment by ktf** [comment]
@dberzano

**Comment by dberzano** [comment]
Hmm, it's unclear to me. Isn't #173 enough?

If the meaning is "do not proceed with alienv enter in case one of the dependencies is missing/fails to load", we are unfortunately clashing with a (IMHO) misbehavior of `modulecmd`: exit code is always 0 even when one or more dependencies are missing.

I am afraid it is impossible to check this case without endlessly grepping porcelain output...

**Comment by dberzano** [comment]
Can we close this? As said with `modulecmd` there's no way of doing that.
