### ISSUE TITLE
aliBuild frendlier architecture recognition

### ISSUE THREAD

**Issue by graffaele** [alisw/alibuild#189]
Ciao Giulio,

Maybe the architecture recognition can be extended for some other common GNU/Linux distributions. In my case for example I get:
>>> platform.dist()
('LinuxMint', '17.3', 'rosa')
>>> lsb_release.get_lsb_information() 
{'RELEASE': '17.3', 'CODENAME': 'rosa', 'ID': 'LinuxMint', 'DESCRIPTION': 'Linux Mint 17.3 Rosa'}
From which I understand that I should launch the script with "-a ubuntu1404_x86-64" since in /etc/os-release I see "VERSION="14.04.4 LTS, Trusty Tahr". It would be nice if that could be taken care by the script itself.

Cheers, ciao,
  Raffaele

**Comment by ktf** [comment]
Agreed it would be nice. The easiest thing, of course, is simply to have "mint173_x86-64" as a (auto-detected) platform. To map it to a proper ubuntu, could you please give me the whole os-release contents?

**Comment by graffaele** [comment]
cat /etc/os-release below. My worry was that you don't have to change the script for each undetected distribution or distribution version, but maybe the effort to let the script search for this info (e.g. parsing /etc/os-release for the Mint case) might not be worth. Ciao, Raffaele

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by ktf** [comment]
Can you please check if #203 works fine on your setup?

**Comment by graffaele** [comment]
It works fine in my case. Thanks.
