### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#205]

**Comment by akubera** [comment]
As was briefly discussed in #216 , I have created a preliminary python3 compatibility branch [here](https://github.com/akubera/alibuild/tree/feature-python3-compat) (it has been rebased to 'alibuild/next'). It hasn't been tested at all, and I'd like to use it more before making the pull request. I invite anybody else to help look for bugs/corner cases.

Please look at it and let me know what you think.

**Comment by ktf** [comment]
This is great, thanks. I opened a new PR, let's discuss things there.

**Comment by ktf** [comment]
The next branch, soon to become 1.4.0.rc1 , should fully support python3. Please let open separate tickets if this is not the case. Closing this.
