### ISSUE TITLE
ROOT does not compile with GCC-toolchain

### ISSUE THREAD

**Issue by rqwa** [alisw/alibuild#209]
Installing ROOT with alibuild and custom GCC-toolchain on SL 6.6 fails (same enviroment as #208). The following components are loaded via `module load ...`:
Python 2.7.8
cmake version 2.8.12.1
gcc 5.2.0

For the installation process I used the following commands:
aliBuild init AliRoot,AliPhysics -z ali-master
aliDoctor 2>&1 | tee -a alidoctor.log
aliBuild -z -w ../sw build AliPhysics --jobs 10 --disable fastjet 2>&1 | tee -a build.log

ROOT compilation fails after 76%, see attached log. The error causing the problem, probably is in line 3164 of the log file. 
[alidoctor.log.txt](https://github.com/alisw/alibuild/files/226072/alidoctor.log.txt)
[build.log.txt](https://github.com/alisw/alibuild/files/226073/build.log.txt)
[log.txt](https://github.com/alisw/alibuild/files/226075/log.txt)

**Comment by ktf** [comment]
Can you try without gcc 5.2.0 in a pristine area? I suspect it's some weird interaction with it.

**Comment by rqwa** [comment]
I will try it without loading any specific gcc version, then this should be 4.4.7

**Comment by rqwa** [comment]
The problem is not in the gcc version, I tested it with gcc 4.4.7 and the custom gcc-toolchain and got the same error.
As I had the same error with the alice-env script, I changed the python version from 2.7.8 to 2.7.3 and got the same error. Anyhow the error disappeared when changing the python version to 2.6.6.

**Comment by rqwa** [comment]
I was able to reproduce the error under Fedora 23.
I installed python 2.7.8 as environment-module. Then loaded python 2.7.8 and started alibuild with the following commands:
aliBuild init AliRoot,AliPhysics -z ali-master --force-unknown-architecture --disable=fastjet
aliBuild -z -w ../sw build AliPhysics --force-unknown-architecture --disable fastjet,GCC-Toolchain 2>&1 | tee -a build.log

[log.txt](https://github.com/alisw/alibuild/files/250092/log.txt)
[build.log.txt](https://github.com/alisw/alibuild/files/250093/build.log.txt)

**Comment by rqwa** [comment]
After some more research I found that this is known problem
https://root.cern.ch/phpBB3/viewtopic.php?t=20744
and also how this issue can be solved:
https://stackoverflow.com/questions/629961/how-can-i-set-ccshared-fpic-while-executing-configure

**Comment by dberzano** [comment]
Hello @rqwa, do you still experience this issue after the latest updates (aliBuild 1.3.0, alidist IB/v5-08/next)? In case, could we follow up in alidist issues instead of here? Thanks!

**Comment by rqwa** [comment]
Hello @dberzano the issue still exists. See [alidist #431](https://github.com/alisw/alidist/issues/431).
