### ISSUE TITLE
Different development branches of same software not handled correctly

### ISSUE THREAD

**Issue by dstocco** [alisw/alibuild#212]
Hi all,
I've installed two different development versions of aliroot.
For one, I just use the master:
aliBuild init -w ../sw AliRoot@master,AliPhysics -z ali-master --dist IB/v5-08/next

and for the other, I need a specific branch:
aliBuild init -w ../sw AliRoot -z ali-muonhlt --dist IB/v5-08/next
cd ali-muonhlt/AliRoot
git checkout feature-muonhlt

When I compile:
in ali-master: aliBuild -z -w ../../sw --disable GEANT4,GEANT4_VMC build AliPhysics
and 
in ali-muonhlt: aliBuild -z -w ../../sw --disable GEANT4,GEANT4_VMC build AliRoot

I find this in the BUILD directory:
AliRoot-latest -> d20faaa6662993d882eef0df002b58f08e8754d0
AliRoot-latest-ali-master -> d20faaa6662993d882eef0df002b58f08e8754d0
AliRoot-latest-ali-muonhlt -> d20faaa6662993d882eef0df002b58f08e8754d0

i.e., despite the AliRoot source code is different (I have the AliRoot master in ali-master and the branch feature-muonhlt in ali-muonhlt), the two different builds are assigned the same hashtag...and each time I compile one of the two, I automatically destroy the other.

Is there some options that I'm missing which would provide a clearly separate build for two clearly different development versions?

Thanks in advance,
best regards,
Diego

**Comment by ktf** [comment]
It does look like a bug. I will look into it ASAP.

**Comment by dberzano** [comment]
Hello @dstocco, I can reproduce the problem, this is indeed a bug. I am looking into it, hopefully will have a fix as soon as possible (as this is quite clearly an annoyance for most people).

**Comment by dberzano** [comment]
Currently in `next`, will make a release soon.

**Comment by dstocco** [comment]
Ciao Dario,
thanks for the work.
I tried it pulling the latest master, but it now seems that the BUILD part is broken again.
I have two custom AliRoot:
ali-master => I put a branch "patches" in it
ali-muonhlt => I put branch "devmuonhlt" in it
When I compile with the latest alibuild, here is what I have in sw/BUILD/AliRoot:
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:15 AliRoot-latest-ali-master -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71
lrwxr-xr-x  1 dstocco  staff   40 May  9 11:14 AliRoot-latest-ali-muonhlt -> 9c7f02f48a368ab51f481e7100661808ff7f0e2f
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:03 AliRoot-latest-devmuonhlt -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:20 AliRoot-latest-patches -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71

The link AliRoot-latest-ali-muonhlt was created when you first "fixed" the issue (before re-opening it). In that case, the different development versions were indeed correctly built in different directories (although they were installed in the same).

It seems now that the two packages still share the same build directory. Is there something that needs to be done on my side (e.g. remove the BUILD directory and start from scratch) in order to make it work?

Thanks,
ciao,
Diego

**Comment by dberzano** [comment]
Hello @dstocco, I have just reproduced your environment from scratch by using the aliBuild version coming from #268.

* An `ali-master` directory with AliRoot on a `patches` branch
* An `ali-muonhlt` directory with AliRoot on a `devmuonhlt` branch

Branches were created with `git checkout -b`.

I have built them using `aliBuild` and the result in the build directory is:

```
$> ls -l ../sw/BUILD/
total 8
drwxrwxr-x 3 dberzano dberzano 4096 May 25 16:28 2d1dc6674f8204d31d1555bcb073c6b3ab5cd230
drwxrwxr-x 3 dberzano dberzano 4096 May 25 17:09 6afd4084aacd34e90996bc698309ec9d96cf176f
lrwxrwxrwx 1 dberzano dberzano   40 May 25 16:28 AliRoot-latest -> 2d1dc6674f8204d31d1555bcb073c6b3ab5cd230
lrwxrwxrwx 1 dberzano dberzano   40 May 25 16:28 AliRoot-latest-ali-master -> 2d1dc6674f8204d31d1555bcb073c6b3ab5cd230
lrwxrwxrwx 1 dberzano dberzano   40 May 25 15:41 AliRoot-latest-ali-muonhlt -> 6afd4084aacd34e90996bc698309ec9d96cf176f
```

As you can see:

* there are no symlinks having the branch name (as opposed to the "tuple" name)
* the only two directories created have the "tuple" name
* those directories are distinct

In practice aliBuild seems to work and I cannot reproduce your situation :-(

In your `ls` output I see that the timestamps are up-to-date (except one), so you have clearly run `aliBuild` just before filing the bug report.

Are you 100% sure you have used the correct version of `aliBuild`? Can you post a `git show` of your `aliBuild` directory please?

Cheers

d.

**Comment by dstocco** [comment]
Ciao Dario,
well, I'm using the latest master, with the related commit (see git show below).

I've just tried to remove the "dev-muonhlt" symlink and the old "ali-muonhlt" related directories and link in the BUILD directory (that were correctly produced just after you first closed the bug).

I tried again, but as soon as I try, here is what I have:
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:15 AliRoot-latest-ali-master -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:20 AliRoot-latest-patches -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:41 AliPhysics-latest-patches -> c33679413dc334a34f2eb566323aa6fa16f8f7c6
lrwxr-xr-x  1 dstocco  staff   40 May 25 09:41 AliPhysics-latest -> c33679413dc334a34f2eb566323aa6fa16f8f7c6
lrwxr-xr-x  1 dstocco  staff   40 May 25 17:34 AliRoot-latest-devmuonhlt -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71
lrwxr-xr-x  1 dstocco  staff   40 May 25 17:34 AliRoot-latest -> 9be466782184285ab7dbf2aa1b3c32ccbee08e71

Know, just to let you know, here is my src dir:
ls -l ali-muonhlt:
drwxr-xr-x  32 dstocco  staff  1088 Apr 18 14:13 O2
drwxr-xr-x  96 dstocco  staff  3264 May 16 11:26 alidist
lrwxr-xr-x   1 dstocco  staff    24 May 19 00:07 AliRoot -> ../../aliroot/devmuonhlt

i.e. AliRoot is a actually a symlink (and to be more specific, a symlink to a git-new-workdir).
The AliRoot in ali-master is also a symlink to another git-new-workdir.
I do not know how you build the hash...but maybe it is this that it doesn't like?

Thanks,
Cheers,
Diego

commit 89ab5916cf026a36ac851c7e491cdc4a0f1ab2eb
Author: Dario Berzano <dario.berzano@gmail.com>
Date:   Tue May 24 10:55:57 2016 +0200

    Use develPrefix as version for devel packages (#268)
    
    This fixes #212: in case two different `develPrefix`es are used for two
    builds, build directories are different (as the hashes will differ) and
    installation directories will be different too (as the version is used in the
    directory name).
    
    To prevent people currently using `ali-master` as `develPrefix` to have
    everything rebuilt because of the hash change, this fix does not apply in that
    case.

diff --git a/aliBuild b/aliBuild
index 6a933af..37a8d5d 100755
--- a/aliBuild
+++ b/aliBuild
@@ -852,6 +852,9 @@ if __name__ == "__main__":
                              defaults_upper=defaults_upper,
                              **nowKwds)
 
+    if spec["package"] in develPkgs and "develPrefix" in args and args.develPrefix != "ali-master":
+      spec["version"] = args.develPrefix
+
   # Decide what is the main package we are building and at what commit.
   #
   # We emit an event for the main package, when encountered, so that we can use
@@ -902,15 +905,12 @@ if __name__ == "__main__":
       h(specs[dep]["hash"])
     if bool(spec.get("force_rebuild", False)):
       h(str(time.time()))
-    if p in develPkgs:
-      if "incremental_recipe" in spec:
-        h(spec["incremental_recipe"])
-        incremental_hash = hashlib.sha1(spec["incremental_recipe"]).hexdigest()
-        spec["incremental_hash"] = "INCREMENTAL_BUILD_HASH=%s" % incremental_hash
-      else:
-        h(spec.get("devel_hash"))
-      if "develPrefix" in args:
-        h(args.develPrefix)
+    if spec["package"] in develPkgs and "incremental_recipe" in spec:
+      h(spec["incremental_recipe"])
+      incremental_hash = hashlib.sha1(spec["incremental_recipe"]).hexdigest()
+      spec["incremental_hash"] = "INCREMENTAL_BUILD_HASH=%s" % incremental_hash
+    elif p in develPkgs:
+      h(spec.get("devel_hash"))
     spec["hash"] = h.hexdigest()
     debug("Hash for recipe %s is %s" % (p, spec["hash"]))

**Comment by ktf** [comment]
Ciao,

can you try using the current tip of the "next" branch?

-- 
Ciao,
Giulio

**Comment by dstocco** [comment]
Ciao Dario, Giulio,
actually, I was thinking about it yesterday, and I think I found out what was wrong.
I realised I was compiling without the -z option. I've added it. I'm waiting for the compilation to finish but what I can already say is that now I have what expected in the BUILD directory....

Sorry for the noise.
Ciao,
Diego

**Comment by dstocco** [comment]
Hi all,
yes, I confirm that with option -z everything is working as expected.

My apologies for the noise.
Thanks!
Ciao,
Diego

**Comment by dberzano** [comment]
Molto bene! We are about to release.
