### ISSUE TITLE
alienv enter fails errors for O2 on CC7

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#220]
After installing O2 using alibuild, I try to set the environment : 

> [eulisse@aidrefflp01 barth]$ alibuild/alienv enter VO_ALICE@O2::latest
BASE/1.0(6):ERROR:105: Unable to locate a modulefile for 'Boost/v1.59.0-1'
BASE/1.0(6):ERROR:105: Unable to locate a modulefile for 'Boost/v1.59.0-1'

You can see it here : eulisse@aidrefflp01:/home/eulisse/barth

**Comment by ktf** [comment]
Should be fixed by alisw/alidist#364 I've also fixed it in place.

**Comment by Barthelemy** [comment]
I have just tried it out and I get the following now : 

> GCC-Toolchain/v4.9.3-1(19):ERROR:105: Unable to locate a modulefile for 'Toolchain/GCC-v4.9.3'

**Comment by ktf** [comment]
This is innocuous actually, can you confirm you have the rest of the environment set correctly? This is already noted in alisw/alibuild#249 and will be fixed at some point.

**Comment by Barthelemy** [comment]
It seems to be good !
