### ISSUE TITLE
Capitalization errors in dependencies lead to inconsistent behaviour

### ISSUE THREAD

**Issue by dberzano** [alisw/alibuild#242]
A dependency listed in require: is pulled in correctly but the depending package does not get built. See e.g. the change required for pythia6 in alisw/alidist#278.

**Comment by dberzano** [comment]
@qgp, moved here for consistency. The original one was alisw/alidist#372.

**Comment by ktf** [comment]
This is a duplicate of #234.

**Comment by dberzano** [comment]
Indeed. Closing it.
