### ISSUE TITLE
Confused with pip

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#260]
Just did a pip upgrade and now I get : 

aliBuild -z -w ../sw --disable fastjet,GEANT4,GEANT4_VMC,HepMC,EPOS,JEWEL build AliRoot
  File "/usr/local/bin/aliBuild", line 33
    except Exception, e:
                    ^
SyntaxError: invalid syntax

I know very little about pip and python but I was expecting python 2.7 to be used, while I see a ref to python 3 there : 

> pip install --upgrade alibuild
Requirement already up-to-date: alibuild in /usr/local/lib/python3.5/site-packages
Requirement already up-to-date: argparse in /usr/local/lib/python3.5/site-packages (from alibuild)
Requirement already up-to-date: pyyaml in /usr/local/lib/python3.5/site-packages (from alibuild)

so I guess I have a mixup of Python versions... I actually have both python2.7 and python3 installed via brew

❯ ll /usr/local/bin/pip*
lrwxr-xr-x  1 laurent  admin  31 May  4 13:11 /usr/local/bin/pip -> ../Cellar/python/2.7.11/bin/pip
lrwxr-xr-x  1 laurent  admin  32 May  4 13:11 /usr/local/bin/pip2 -> ../Cellar/python/2.7.11/bin/pip2
lrwxr-xr-x  1 laurent  admin  34 May  4 13:11 /usr/local/bin/pip2.7 -> ../Cellar/python/2.7.11/bin/pip2.7
lrwxr-xr-x  1 laurent  admin  32 May  4 18:15 /usr/local/bin/pip3 -> ../Cellar/python3/3.5.1/bin/pip3
lrwxr-xr-x  1 laurent  admin  34 May  4 18:15 /usr/local/bin/pip3.5 -> ../Cellar/python3/3.5.1/bin/pip3.5

~/alicesw/run2/aliroot-master
❯ pip --version
pip 8.1.1 from /usr/local/lib/python3.5/site-packages (python 3.5)

~/alicesw/run2/aliroot-master
❯ which pip
/usr/local/bin/pip

~/alicesw/run2/aliroot-master
❯ /usr/local/bin/pip --version
pip 8.1.1 from /usr/local/lib/python3.5/site-packages (python 3.5)

and I actually tried to remove alibuild and reinstall it using pip uninstall but as that was pip3, I'm now in a situation where pip2 thinks he has alibuild while it has not...

Any advice warmly welcome ;-)

**Comment by ktf** [comment]
Ciao,

- If you do not use python3, I recommend disinstalling it and run pip install again (`brew uninstall python3`, I guess).
- If you do use python3 and you do not want to uninstall it, you can try installing it with `pip2` and then change the default python to be 2.7.

We have making aliBuild python3 compatible on the todo list (see #205).

**Comment by aphecetche** [comment]
Hi,

Well, I do use python3, quite indirectly through a vim plugin (now, whether I should be using vim at all is another debate ;-) ). So yes, I'd like to keep it around.

Problem is that pip2 is convinced that alibuild is already installed, while it's not the case... Is there a way to force it to re-install ?

**Comment by aphecetche** [comment]
ok, forget it : 

pip2 uninstall alibuild
pip2 install alibuild

did it.
