### ISSUE TITLE
Don't rebuild local packages if nothing has changed

### ISSUE THREAD

**Issue by sawenzel** [alisw/alibuild#270]
Currently local packages clones are always rebuild. It would be nice to avoid this by hashing/cashing on the last commit + the last local diff

**Comment by ktf** [comment]
agreed.

**Comment by dberzano** [comment]
See #282. @sawenzel, could you give it a try?

**Comment by sawenzel** [comment]
Works nicely in a first test. I am closing the issue and I appreciate the quick implementation.
