### ISSUE TITLE
Feature request: Add option for latest tag

### ISSUE THREAD

**Issue by rqwa** [alisw/alibuild#271]
Would it be possible to add an option to install the latest tag/daily-tag of AliRoot/AliPhysics, i.e.:
aliBuild init AliRoot@v5-latest(for latest v5 tag),AliPhysics@vAN-latest (for latest daily tag) -z ali-current

By running this option alibuild checks if a newer tag then the installed is available and install the version if necessary. After the installation the most current versions are installed and there is no need to check what the latest available versions are.

**Comment by ktf** [comment]
We should probably have a post processing job for each (correctly compiled) daily which updates alidist/aliphysics.sh and alidist/aliroot.sh with the latest successfully built tag. This way you simply do:

```
pushd alidist
git pull
popd
aliBuild build AliPhysics
```

and get the expected result. To be discussed.

**Comment by rqwa** [comment]
If this feature is implemented it should not only be implemented for daily tags, but also for releases. As those provide a version which will be long-time available on the grid.

**Comment by dberzano** [comment]
Closing this: with the new version of aliBuild (1.5.0rc1, currently being tested) it is possible to add a `defaults` which does exactly what you need without touching aliBuild. I am opening a ticket there.

**Comment by dberzano** [comment]
See #466 and #476.
