### ISSUE TITLE
wrong analytics url when executing aliBuild

### ISSUE THREAD

**Issue by vascobarroso** [alisw/alibuild#300]
This URL is broken:

==> In order to improve user experience, aliBuild would like to gather analytics about your builds.
    You can find all the details at:
    
      https://github.com/alisw/alibuild/blob/master/Analytics.md

This seems to be the correct URL:

https://github.com/alisw/alibuild/blob/master/ANALYTICS.md

**Comment by ktf** [comment]
Thanks. Fixed in #303.
