### ISSUE TITLE
Root installation fails

### ISSUE THREAD

**Issue by kouzinopoulos** [alisw/alibuild#311]
Trying to build the software stack using AliBuild on Ubuntu 16.04. During the building process, compilation of ROOT breaks with the following message:

DEBUG:O2:0: [ 78%] Building CXX object roofit/roofitcore/CMakeFiles/RooFitCore.dir/src/RooChangeTracker.cxx.o
DEBUG:O2:0: [ 78%] Linking CXX shared library ../../lib/libRooFitCore.so
DEBUG:O2:0: [ 78%] Built target RooFitCore
DEBUG:O2:0: Makefile:149: recipe for target 'all' failed
DEBUG:O2:0: make: *** [all] Error 2
DEBUG:O2:0: 
ERROR:O2:0: Error while executing /opt/alice/sw/SPECS/ubuntu1604_x86-64/ROOT/v5-34-30-alice-1/build.sh on `charis-Inspiron-7537'.
ERROR:O2:0: Log can be found in /opt/alice/sw/BUILD/ROOT-latest/log.
ERROR:O2:0: Please attach this file if you intend to request support.
ERROR:O2:0: Build directory is /opt/alice/sw/BUILD/ROOT-latest/ROOT.

AliBuild version:

charis@charis-Inspiron-7537:/opt/alice/alibuild (master)$ git log | awk 'NR==1'
commit fa4262b2702448417f351854730e9a75b1a10454

AliDist version:

charis@charis-Inspiron-7537:/opt/alice/alidist (IB/v5-08/prod)$ git log | awk 'NR==1'
commit 17aab49f0373df33e6b3408fa3d05f2f00c550a4

**Comment by ktf** [comment]
Can you tell me what aliDoctor ROOT says?

**Comment by kouzinopoulos** [comment]
I am invoking alibuild with the --disable GCC-Toolchain flag. The aliDoctor message is as follows:

alibuild/aliDoctor ROOT
WARNING: Package GSL cannot be picked up from the system and will be built by aliBuild.
WARNING: This is due to the fact the following script fails:
WARNING: 
WARNING: brew() { true; }; printf "#include \"gsl/gsl_version.h\"\n# if (GSL_MAJOR_VERSION * 100 + GSL_MINOR_VERSION < 116)\n#error \"Cannot use system's gsl.\"\n#endif\nint main(){}" | gcc  -I$(brew --prefix gsl)/include -xc++ - -o /dev/null
WARNING: 
WARNING: with the following output:
WARNING: 
WARNING: GSL: <stdin>:1:29: fatal error: gsl/gsl_version.h: No such file or directory
WARNING: GSL: compilation terminated.
WARNING: GSL: 
WARNING: 
WARNING: Package GCC-Toolchain cannot be picked up from the system and will be built by aliBuild.
WARNING: This is due to the fact the following script fails:
WARNING: 
WARNING: brew() { true; }; printf "#if ((__GNUC__ << 16)+(__GNUC_MINOR__ << 8)+(__GNUC_PATCHLEVEL__) < (0x040800)) || ((__GNUC__ << 16)+(__GNUC_MINOR__ << 8)+(__GNUC_PATCHLEVEL__) >= (0x050000))\n#error \"Cannot use system's, GCC building our own.\"\n#endif\n" | gcc -xc++ - -c -o /dev/null
WARNING: 
WARNING: with the following output:
WARNING: 
WARNING: GCC-Toolchain: <stdin>:2:2: error: #error "Cannot use system's, GCC building our own."
WARNING: GCC-Toolchain: 
WARNING: 
SUCCESS: Package zlib will be picked up from the system.
SUCCESS: Package libxml2 will be picked up from the system.
SUCCESS: Package OpenSSL will be picked up from the system.
WARNING: Package autotools cannot be picked up from the system and will be built by aliBuild.
WARNING: This is due to the fact the following script fails:
WARNING: 
WARNING: brew() { true; }; PATH=$PATH:$(brew --prefix gettext || true)/bin && which autoconf && which m4 && which automake && which makeinfo && which aclocal && which pkg-config && which autopoint && which libtool
WARNING: 
WARNING: with the following output:
WARNING: 
WARNING: autotools: 
WARNING: 
SUCCESS: Package CMake will be picked up from the system.
SUCCESS: Package SWIG will be picked up from the system.
SUCCESS: Required package libperl will be picked up from the system.

==> The following packages will be picked up from the system:
    
    - libxml2
    - SWIG
    - zlib
    - CMake
    - OpenSSL
    
    If this is not you want, you have to uninstall / unload them.

==> The following packages will be build by aliBuild because they couldn't be picked up from the system:
    
    - GCC-Toolchain
    - autotools
    - GSL
    
    This is not a real issue, but it might take longer the first time you invoke aliBuild.

**Comment by kouzinopoulos** [comment]
It seems that a similar error is happening with GCC-Toolchain:

ust a directory name.
/bin/bash ../../../gcc/libgcc/../mkinstalldirs .
/opt/alice/sw/BUILD/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/GCC-Toolchain/build-gcc/./gcc/xgcc -B/opt/alice/sw/BUILD/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/GCC-Toolchain/build-gcc/./gcc/ -B/opt/alice/sw/INSTALLROOT/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/ubuntu1604_x86-64/GCC-Toolchain/v4.9.3-1/x86_64-unknown-linux-gnu/bin/ -B/opt/alice/sw/INSTALLROOT/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/ubuntu1604_x86-64/GCC-Toolchain/v4.9.3-1/x86_64-unknown-linux-gnu/lib/ -isystem /opt/alice/sw/INSTALLROOT/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/ubuntu1604_x86-64/GCC-Toolchain/v4.9.3-1/x86_64-unknown-linux-gnu/include -isystem /opt/alice/sw/INSTALLROOT/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/ubuntu1604_x86-64/GCC-Toolchain/v4.9.3-1/x86_64-unknown-linux-gnu/sys-include    -O2  -g -O2 -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -mlong-double-80 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector  -shared -nodefaultlibs -Wl,--soname=libgcc_s.so.1 -Wl,--version-script=libgcc.map -o ./libgcc_s.so.1.tmp -g -O2 -B./ _muldi3_s.o _negdi2_s.o _lshrdi3_s.o _ashldi3_s.o _ashrdi3_s.o _cmpdi2_s.o _ucmpdi2_s.o _clear_cache_s.o _trampoline_s.o __main_s.o _absvsi2_s.o _absvdi2_s.o _addvsi3_s.o _addvdi3_s.o _subvsi3_s.o _subvdi3_s.o _mulvsi3_s.o _mulvdi3_s.o _negvsi2_s.o _negvdi2_s.o _ctors_s.o _ffssi2_s.o _ffsdi2_s.o _clz_s.o _clzsi2_s.o _clzdi2_s.o _ctzsi2_s.o _ctzdi2_s.o _popcount_tab_s.o _popcountsi2_s.o _popcountdi2_s.o _paritysi2_s.o _paritydi2_s.o _powisf2_s.o _powidf2_s.o _powixf2_s.o _mulsc3_s.o _muldc3_s.o _mulxc3_s.o _divsc3_s.o _divdc3_s.o _divxc3_s.o _bswapsi2_s.o _bswapdi2_s.o _clrsbsi2_s.o _clrsbdi2_s.o _fixunssfsi_s.o _fixunsdfsi_s.o _fixunsxfsi_s.o _fixsfdi_s.o _fixdfdi_s.o _fixxfdi_s.o _fixunssfdi_s.o _fixunsdfdi_s.o _fixunsxfdi_s.o _floatdisf_s.o _floatdidf_s.o _floatdixf_s.o _floatundisf_s.o _floatundidf_s.o _floatundixf_s.o _divdi3_s.o _moddi3_s.o _udivdi3_s.o _umoddi3_s.o _udiv_w_sdiv_s.o _udivmoddi4_s.o cpuinfo_s.o sfp-exceptions_s.o addtf3_s.o divtf3_s.o multf3_s.o negtf2_s.o subtf3_s.o unordtf2_s.o fixtfsi_s.o fixunstfsi_s.o floatsitf_s.o floatunsitf_s.o fixtfdi_s.o fixunstfdi_s.o floatditf_s.o floatunditf_s.o fixtfti_s.o fixunstfti_s.o floattitf_s.o floatuntitf_s.o extendsftf2_s.o extenddftf2_s.o extendxftf2_s.o trunctfsf2_s.o trunctfdf2_s.o trunctfxf2_s.o getf2_s.o letf2_s.o eqtf2_s.o _divtc3_s.o _multc3_s.o _powitf2_s.o enable-execute-stack_s.o unwind-dw2_s.o unwind-dw2-fde-dip_s.o unwind-sjlj_s.o unwind-c_s.o emutls_s.o libgcc.a -lc && rm -f ./libgcc_s.so && if [ -f ./libgcc_s.so.1 ]; then mv -f ./libgcc_s.so.1 ./libgcc_s.so.1.backup; else true; fi && mv ./libgcc_s.so.1.tmp ./libgcc_s.so.1 && ln -s libgcc_s.so.1 ./libgcc_s.so
/opt/alice/sw/INSTALLROOT/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/ubuntu1604_x86-64/GCC-Toolchain/v4.9.3-1/x86_64-unknown-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/crti.o: unrecognized relocation (0x2a) in section `.init'
/opt/alice/sw/INSTALLROOT/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/ubuntu1604_x86-64/GCC-Toolchain/v4.9.3-1/x86_64-unknown-linux-gnu/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:937: recipe for target 'libgcc_s.so' failed
make[3]: *** [libgcc_s.so] Error 1
make[3]: Leaving directory '/opt/alice/sw/BUILD/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/GCC-Toolchain/build-gcc/x86_64-unknown-linux-gnu/libgcc'
Makefile:19068: recipe for target 'all-stage1-target-libgcc' failed
make[2]: *** [all-stage1-target-libgcc] Error 2
make[2]: Leaving directory '/opt/alice/sw/BUILD/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/GCC-Toolchain/build-gcc'
Makefile:23314: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/opt/alice/sw/BUILD/1f6d3650e4bbfa5c248ad8b4bf901fb5a709ea9a/GCC-Toolchain/build-gcc'
Makefile:23741: recipe for target 'bootstrap-lean' failed
make: *** [bootstrap-lean] Error 2

And the output of aliDoctor:

charis@charis-Inspiron-7537:/opt/alice$ alibuild/aliDoctor GCC-Toolchain
WARNING: Package GCC-Toolchain cannot be picked up from the system and will be built by aliBuild.
WARNING: This is due to the fact the following script fails:
WARNING: 
WARNING: brew() { true; }; printf "#if ((__GNUC__ << 16)+(__GNUC_MINOR__ << 8)+(__GNUC_PATCHLEVEL__) < (0x040800)) || ((__GNUC__ << 16)+(__GNUC_MINOR__ << 8)+(__GNUC_PATCHLEVEL__) >= (0x050000))\n#error \"Cannot use system's, GCC building our own.\"\n#endif\n" | gcc -xc++ - -c -o /dev/null
WARNING: 
WARNING: with the following output:
WARNING: 
WARNING: GCC-Toolchain: <stdin>:2:2: error: #error "Cannot use system's, GCC building our own."
WARNING: GCC-Toolchain: 
WARNING: 
WARNING: Package autotools cannot be picked up from the system and will be built by aliBuild.
WARNING: This is due to the fact the following script fails:
WARNING: 
WARNING: brew() { true; }; PATH=$PATH:$(brew --prefix gettext || true)/bin && which autoconf && which m4 && which automake && which makeinfo && which aclocal && which pkg-config && which autopoint && which libtool
WARNING: 
WARNING: with the following output:
WARNING: 
WARNING: autotools: 
WARNING: 

==> The following packages will be build by aliBuild because they couldn't be picked up from the system:
    
    - GCC-Toolchain
    - autotools
    
    This is not a real issue, but it might take longer the first time you invoke aliBuild.

**Comment by ktf** [comment]
Which branch are you using? Can you switch to `IB/v5-08/o2`? That should fix your problem. You might also want to install autoconf, automake, texinfo, pkg-config and libtool so that you do not need to rebuild autotools.

**Comment by dberzano** [comment]
@kouzinopoulos, did you try the proposed solution? Did it work?

**Comment by ktf** [comment]
Final ping before closing this. ;-)
