### ISSUE TITLE
Unable to build with docker

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#335]
On CC7 I am unable to build with docker : 

> [eulisse@aidrefflp01 barth]$ alibuild/aliBuild --docker --disable GEANT4_VMC --disable GEANT3 --disable GEANT4 -e slc7_x86-64 build O2
> ...
> ==> Building pythia6@416
> Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
> ERROR: Error while executing /home/eulisse/barth/sw/SPECS/slc7_x86-64/pythia6/416-1/build.sh on `aidrefflp01.cern.ch'.
> ERROR: Log can be found in /home/eulisse/barth/sw/BUILD/pythia6-latest/log.
> ERROR: Please attach this file if you intend to request support.
> ERROR: Build directory is /home/eulisse/barth/sw/BUILD/pythia6-latest/pythia6.
> [eulisse@aidrefflp01 barth]$ cat /home/eulisse/barth/sw/BUILD/pythia6-latest/log
> + cmake /sw/SOURCES/pythia6/416/f401bcd27f -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_INSTALL_PREFIX=/sw/INSTALLROOT/a69d82ff38c36526c4a0e53d18ad2937e7bee2ee/slc7_x86-64/pythia6/416-1
> /sw/SPECS/slc7_x86-64/pythia6/416-1/pythia6.sh: line 3: cmake: command not found

I need it to be able to merge PR-116 in AliceO2.

**Comment by ktf** [comment]
looking into this

**Comment by ktf** [comment]
This is actually an bug in aliBuild, triggered by having cmake on the host, but not in docker. :-/

This needs more work but for the moment you should be able to replicate the environment in the integration builds passing `--no-system`.

**Comment by ktf** [comment]
See also #339. Closing this.

**Comment by ktf** [comment]
#354 should fix this. Will be in 1.4.0.
