### ISSUE TITLE
How to build "development" packages when they fail to compile ?

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#351]
Ok, title is weird, let me try to explain. 

I have O2 checked out in ~/alice. I do `alibuild/alibuild build O2` and it fails in O2. At this stage, I would like to be able to go to ~/alice/sw/BUILD/O2-latest and rebuild only O2 with different options (typicall VERBOSE=1). But I lack the whole environment and if I do `alibuild/alienv enter O2` it will complain that O2 is not available. 

Let me know if it is not clear.

**Comment by ktf** [comment]
Yeah, I actually have an open bug report in AliceO2Group/AliceO2#98 . I suggest we track it there.

As discussed a workaround would be:

```
alienv enter ROOT/latest
cd ~/alice/sw/BUILD/O2-latest/O2
make -j 20 install
```
notice that you also need the last "O2"  in the path (which was probably the cause of your issue).
