### ISSUE TITLE
Execute alienv independently from alibuild directory

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alibuild#372]
This is a minor feature request:

Just noticed that alienv needs to be executed either directly from the alibuild directory or the level above. If I want to execute it from e.g. my home directly like
    ~/src/alisw/alibuild/alienv q

I just get the help. If technically possible, it would be a nice feature to be able to execute it from any directory.

**Comment by ktf** [comment]
doesn't

```
export ALICE_WORK_DIR=~/sw/alisw/sw
```

(or wherever you have your stuff) work?

**Comment by dberzano** [comment]
Currently, `ALICE_WORK_DIR` is not honored by `alienv`, but by the shell helper, which I admit is not optimal.

#474 should, among other things, sort this issue out too:

* you can use an environment variable which is your default `sw` directory
* `alienv` will use it also without the shell helper
* it's taken into consideration by `aliBuild` too

**Comment by matthiasrichter** [comment]
thanks, I think this is done, closing the issue
