### ISSUE TITLE
ROOT6 build fails on MacOSX (10.12.1) in Python-modules

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#386]
> aliBuild init ROOT -z root6
> cd root6
> aliBuild --defaults root6 -z -d -w ../sw build ROOT

stops at Python-modules, see attached log.

[log.txt](https://github.com/alisw/alibuild/files/604060/log.txt)

**Comment by aphecetche** [comment]
Hi,

This one I solved using : 

pip install pytz

But now I run into (what I believe is) a variation of the already reported issue https://github.com/alisw/alidist/issues/536 (Diego's issue is with libsodium, mine is with libGSL)

[ 69%] Linking CXX shared library ../../../lib/libSerializationExample.dylib
ld: file not found: /Users/laurent/alicesw/run3/sw/INSTALLROOT/9c76dec5900632732ff0b2f3dabf8c2a314eb832/osx_x86-64/GSL/v1.16_O2-1/lib/libgsl.0.dylib for architecture x86_64

**Comment by ktf** [comment]
I assume this can be closed. Reopen if not the case.
