### ISSUE TITLE
O2 build stops at ROOT

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alibuild#390]
Building O2 from scratch in an empty directory on Ubuntu 14.04
alibuild `master` `59ca01a`
alidist `IB/v5-08/prod` `b72c948`

Running: `alibuild/aliBuild --defaults o2 build o2`

Stops when building ROOT. There is no log file in `sw/BUILD/ROOT/ROOT-latest/log` 

Interestingly enough, just starting over gets over this point. But it is reproducible, whenever I start in a new directory.

**Comment by matthiasrichter** [comment]
have now verified it on a different machine running Centos

**Comment by matthiasrichter** [comment]
Here is the error message in debug mode
`DEBUG:O2:3bd6b870: error: pathspec 'v6-06-04' did not match any file(s) known to git.`

it looks like tag v6-06-04 has been removed in the ROOT repository.

When starting over, the checkout step is omitted, and build continues, however with the master branch, i.e. wrong version.

**Comment by matthiasrichter** [comment]
@ktf looks like it is a problem with the https://github.com/alisw/root fork. There the tag is missing, while it is existing on the github root mirror https://github.com/root-mirror/root/tree/v6-06-04

**Comment by Barthelemy** [comment]
+1 same here. @ktf @dberzano  could you check ?

**Comment by matthiasrichter** [comment]
Fixed in PR https://github.com/alisw/alidist/pull/576  with https://github.com/alisw/alidist/pull/576/commits/02e0df53f7ccd349070c7d01352c5f7157eeb93d
