### ISSUE TITLE
Make sure builds can happen in path with spaces

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#395]
While having a space in the directory name is kinda awkward, we should nevertheless fail silently and in general make sure this can be done.

**Comment by aphecetche** [comment]
Hi Giulio,

Somehow related to this one I guess (though it might be fixable in the recipe instead ?)

I've lately installed VMWare Fusion 10 on my Mac, and it installs a file in /etc/paths.d : com.vmware.fusion.public which adds "/Applications/VMware Fusion.app/Contents/Public" to the PATH... (note the space between VMWare and Fusion...)

With that PATH in place I'm no longer able to build ROOT with aliBuild : it fails in the test phase when doing "env PATH=.... make" as the env part is split at the space so I end up with something like : 

 Fusion.app/Contents/Public/: .... command not found

**Comment by ktf** [comment]
#941 should fix your problem. Can you check?

**Comment by aphecetche** [comment]
Yes, problem solved, this one can be closed.
