### ISSUE TITLE
Problem with default CXXFLAGS + CFLAGS

### ISSUE THREAD

**Issue by sawenzel** [alisw/alibuild#400]
Our standard defaults set 

`CXXFLAGS="-g -O2 -fPIC -std=c++11"`

I believe there are several disadvantages in doing so at the global level for some flags.

  * We have `-g` for every single package build (even if system library or compiler); This leads to VERY big binaries and slow package building with "tar". 
  * The -O2 option clashes with most `-DCMAKE_BUILD_TYPE=Debug` builds. In fact trying to compile ROOT in Debug option does not do what I want because it still picks up a -O2 from the global setting.

Question/Suggestion:
  * Would it not make sense to set the global CXXFLAGS to the bare minimum and delegate the rest to the options offered by the various CMakeLists.txt configurations?

**Comment by sawenzel** [comment]
Sorry. I realized this should have been opened in alidist. So feel free to move it there.

**Comment by matthiasrichter** [comment]
That would actually also solve the issue with the huge disk space needed for ROOT cling compilation. dropping the ```-g``` option in the reduced the amount of disk space for the ROOT 6 built from 12 GB to 3 GB, and the installation directory from 8 GB to 3 GB. So I would also like to change the default.

**Comment by Barthelemy** [comment]
I am for it. It should be defined at the package level.

**Comment by ktf** [comment]
This is indeed a problem of alidist, not really something alibuild has knowledge about. That said, do we really want to change it globally or just on a per package basis?

**Comment by ktf** [comment]
This is fine for me, however some options, like `-std=c++11`, should be defined at a global level because you need a uniform setting. How do we deal with that?

**Comment by Barthelemy** [comment]
I was talking about "-g -O2". In my opinion, "-fPIC -std=c++11" can stay global.

**Comment by sawenzel** [comment]
I also think we need SOME global setting like "-fPIC -std=c++11" ( and possibly the target architecture like -mavx ). Other settings like compiler optimization and debug flags should be handled on per recipe basis.

**Comment by matthiasrichter** [comment]
Indeed, ```-fPIC -std=c++11``` must be global settings. I volunteer to prepare a PR as proposal we can comment on directly

**Comment by sawenzel** [comment]
I am working on a PR for this. I just realized that removing "-g" from the defaults might not be enough. The default also set a CMAKE_BUILD_TYPE to RelWithDebInfo (almost globally) which still leads to enormous binary sizes + compilation times for ROOT etc. 

Would it be possible to decouple the CMAKE_BUILD_TYPE from the defaults, too?

**Comment by matthiasrichter** [comment]
@dberzano can this issue be moved to alidist (as Sandro mentioned earlier). I knew there was this issue but I did not find it

**Comment by ktf** [comment]
From the discussion I understand this was actually done in alidist. Closing this. Please reopen if not the case.
