### ISSUE TITLE
Print available defaults for a given package

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#401]
As a user I would like to be informed early if a given package is not supposed to work with the current default because I do not want to spend time compiling something is known not to work.

**Comment by dberzano** [comment]
If you now try with #466 to compile O2 without specifying a default you will get:

```
Cannot compile O2 with `release' default. Valid defaults are
 - o2
 - o2-daq
 - o2-dev-fairroot
```

which is what you want (thanks to @ktf). Closing.
