### ISSUE TITLE
Python-modules installation failure (CentOS7)

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#418]
Hi,

I thought I had this one resolved, but apparently not... On a centos7 container (https://github.com/aphecetche/docker-alicore/blob/master/Dockerfile), trying to install ROOT

```bash
bash-4.2$ aliBuild -w $HOME/sw --defaults o2 build ROOT

==> aliBuild can take the following packages from the system and will not build them:
      Python, libpng, FreeType, CMake, GSL

==> The following packages cannot be taken from the system and will be built:
      Python-modules

==> Packages will be built in the following order:
     - defaults-o2@v1
     - Python-modules@1.0
     - ROOT@v6-08-02

==> Building defaults-o2@v1
==> defaults-o2 is being built (use --debug for full output): ok
Using cached build for defaults-o2

==> Building Python-modules@1.0
==> Python-modules is being built (use --debug for full output): failed
ERROR: Error while executing /home/laurent/sw/SPECS/slc7_x86-64/Python-modules/1.0-1/build.sh on `5de45a925b60'.
ERROR: Log can be found in /home/laurent/sw/BUILD/Python-modules-latest/log.
ERROR: Please attach this file if you intend to request support.
ERROR: Build directory is /home/laurent/sw/BUILD/Python-modules-latest/Python-modules.
bash-4.2$ cat /home/laurent/sw/BUILD/Python-modules-latest/log
```

[log.txt](https://github.com/alisw/alibuild/files/754435/log.txt)

**Comment by bazinski** [comment]
I have 2 systems, one works and the other not, both centos7

This is due to a mismatch in pyparsing.
In centos7 pyparsing (base) is 1.5.6.-9.el7
pip has 2.1.10.

Working system has its pyparsing from pip.
Broken system has its from yum, fixing the broken one is another story it seems.

Even building simplegeneric from source on the yum based machine is failing.

In your docker container, Pyparsing is pulled in from your "yum install -y git gettext-devel ....."

building your docker now, it will be a while.

But i fear others will run into this. I suppose one must pick pip or yum to manage python.
In this case I assume the only option is pip ?

**Comment by bazinski** [comment]
perl-ExtUtils-Embed is pulling in pyparsing.

perl-ExtUtils-Embed -> perl-devel -> systemtap-sdt-devel -> pyparsing

**Comment by ktf** [comment]
Can you try updating the pip you have in your container via:

```
pip install --upgrade pip
```

? I am chasing a similar problem as well..

**Comment by bazinski** [comment]
doing pip first, then a yum install perl-ExtUtils-Embed replaces pyparsing with the 1.5.6 version so one can prevent it in the repo file for base.

**Comment by bazinski** [comment]
yes pip is the latest 9 something.

**Comment by bazinski** [comment]
@ktf is git 2.8.3 a requirement for O2 ? my centos install seems to work fine for 1.8.? what eve is standard on centos.

It might be a better solution to use virtenv with alibuild and then negate the possible future conflicts with yum/pip and for that matter apt/pip or others?

**Comment by ktf** [comment]
Any (reasonable) git should be fine.

Regarding virtualenv, indeed that looks like a better solution (I was actually thinking about pyenv).

**Comment by aphecetche** [comment]
@bazinski for the record in my docker image I installed a git > 1.8 because I'm using (so far, might reconsider) the git worktree feature that was introduced in 2.5 I think.
Still, with the same image it used to work just fine, so I suspect something else changed (I know that's not a terribly helpful statement ;-) )

**Comment by bazinski** [comment]
@ktf i have no religious feelings about anything do to with python ;-) pyenv if you like.
@aphecetche I dont really see a way around it then with out either blocking pyparsing in yum config or entering virtualenv or pyenv before firing up alibuild, or maybe building a tar ball of git somewhere else and copying across, but that seems messy.

**Comment by dberzano** [comment]
Is the issue still there? In case, please reopen it in the alidist repository.
