### ISSUE TITLE
Building AliceO2 with gcc 6.2.1

### ISSUE THREAD

**Issue by dest1** [alisw/alibuild#421]
Hi,
I've successfully built AliceO2 with gcc 6.2.1. The only changes needed were:
- get rid of compiler constraints from gcc-toolchain.sh
- move from Vc 1.2.0 to 1.3.0
- use python 2.7 (python modules do not compile with 3.3)
- install autotools by hand

Do you consider making it officially supported aliBuild?
Cheers,
Adam

**Comment by Barthelemy** [comment]
it will be discussed in CWG11 on Friday

**Comment by dberzano** [comment]
I am closing this in favor of more granular issues (we're fixing them all btw).
