### ISSUE TITLE
Python modules fails to compile with python 3.3

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alibuild#422]
Hey,
It failed with python 3.3 (from devtoolset) due to:
"Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython==5.1.0)"
I think additional check should be added.

Cheers,
Adam

**Comment by dberzano** [comment]
Are you referring to the `Python-modules` recipe? You should maybe install the missing modules with `pip` (from devtoolset) in order to prevent our recipe to run at all. Let us know.

**Comment by awegrzyn** [comment]
Indeed I was referring to python modules. Thanks for the hint
