### ISSUE TITLE
alibuild hangs when defaults is used with wrong spelling

### ISSUE THREAD

**Issue by sawenzel** [alisw/alibuild#429]
I was trying to run

`./alibuild/aliBuild build O2 --defaults O2-daq --debug`

instead of the correct spelling

`./alibuild/aliBuild build O2 --defaults o2-daq --debug`

alibuild did not realise that this is an incorrect spelling for a default and started to hang.
It would be useful to perform checks on the spelling of defaults.

**Comment by dberzano** [comment]
It's done now on #466.
