### ISSUE TITLE
Rename alibuild 

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#433]
We discussed the name "lead" as a good candidate. 
It should be backward compatible (people should be able to use the old name).

Moreover, it should add commands to cover the functions of alienv.

**Comment by Barthelemy** [comment]
@ktf

**Comment by matthiasrichter** [comment]
@Barthelemy what would "lead" stand for? To me it does not make much sense, it's not descriptive at all.

**Comment by ktf** [comment]
blei !

**Comment by ktf** [comment]
Regardless of the name, I think it would be go to align it to a single utility with multiple commands:

```
ali build
ali doctor
ali setenv
ali enter
```

and so on. Of course alienv, aliBuild would remain as symlinks, at least until we realise people do not use them anymore (we could actually monitor this via the analytics).

**Comment by Barthelemy** [comment]
@matthiasrichter it is not an abbreviation. It simply has 2 meanings that are connected to 1. the utility (the verb lead) and 2. a specificity of ALICE (the atoms we like to observe colliding). Giulio might be able to give more details as it was his proposal (sorry I did not mean to steal it). 

Any ways, what matters is to have a short and unique name for a utility to which we pass commands. And it should be backward compatible.

**Comment by matthiasrichter** [comment]
The tool is not restricted to ALICE, so we can broaden the scope for the name search. But if we want to follow the "lead" road, we can use pB for "power Build" ;-)

**Comment by ktf** [comment]
I like `pb` as well. Could also mean "People build", a tool by the people for the people... ;-)

**Comment by Barthelemy** [comment]
I like it too !

**Comment by ktf** [comment]
For the record, I've done some preparatory work in the `dev` branch of https://github.com/ktf/alibuild . It's mostly a big refactoring of the internals, however it already allows to have:

```
aliBuild doctor
```

as a subcommand, rather than an actual command. More to come.

**Comment by ktf** [comment]
For the record, my dev branch now sports a "pb" helper which redirects to aliBuild.

**Comment by dberzano** [comment]
`pb` is in #466. Can we close this?

**Comment by Barthelemy** [comment]
yes
