### ISSUE TITLE
--disable not honoured ?

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#440]
Hi, 

Don't know what's broken (on my system ?), but it seems the disable flag is no longer acting as expected.

~/alice/ali-reco-2017
❯ aliBuild -w ../sw --disable generators,simulation build AliRoot

==> aliBuild can take the following packages from the system and will not build them:
      CMake, libxml2, SWIG, zlib, autotools, boost

==> The following packages cannot be taken from the system and will be built:
      GSL

==> Packages will be built in the following order:
     - defaults-release@v1
     - DPMJET@v3.0.5-alice3
     - AliEn-CAs@master
     - Vc@1.2.0
     - UUID@alice/v2.27.1
     - GEANT4@v4.10.01.p03
     - gSOAP@alice/v2.7.13
     - ApMon-CPP@v2.2.8
     - GMP@v6.0.0
     - GSL@release-1-16
     - MonALISA-gSOAP-client@alice/v2.7.10
     - MPFR@v3.1.3
     - XRootD@v3.3.6
     - cgal@v4.6.3%(defaults_upper)s
     - xalienfs@v1.0.14r1-alice1
     - fastjet@v3.2.1_1.024-alice1
     - AliEn-Runtime@v2-19-le%(defaults_upper)s
     - ROOT@v5-34-30-alice7
     - vgm@4.3
     - GEANT3@v2-2
     - GEANT4_VMC@v3-2-p1
     - AliRoot (development package)

==> You have packages in development mode.
    This means their source code can be freely modified under:

      /Users/laurent/alice/ali-reco-2017/<package_name>

    aliBuild does not automatically update such packages to avoid work loss.
    In most cases this is achieved by doing in the package source directory:

      git pull --rebase
^C

❯ aliBuild version
aliBuild version: 1.4.0

~/alice/ali-reco-2017
❯ uname -a
Darwin nanpc420.in2p3.fr 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

**Comment by BerserkerTroll** [comment]
You need to give package names to `--disable`, e.g. `--disable GEANT3,GEANT4_VMC`

**Comment by aphecetche** [comment]
Well, but as simulation and generators are (meta) packages, I would expect to be able to disable them all at once. 

```
~/alice/ali-master/alidist 
❯ more generators.sh
package: generators
version: v1.0
requires:
  - pythia
  - pythia6
---
# A catch all recipe for all the generators.

~/alice/ali-master/alidist 
❯ more simulation.sh
package: simulation
version: v1.0
requires:
  - GEANT4_VMC
  - GEANT4
  - GEANT3
  - HepMC
---
# A catch all recipe for all the generators
```

**Comment by ktf** [comment]
`--disable` removes a node from the DAG. In this particular case `simulation.sh` and `generators.sh` are  not part of the DAG (as you can see from dependency list) and GEANT3 / GEANT4 are explicitly given as dependencies (for historical reasons).

**Comment by ktf** [comment]
Closing this. If not clear, please reopen.
