### ISSUE TITLE
FairRoot's CMake doesn't pick up Boost

### ISSUE THREAD

**Issue by teo** [alisw/alibuild#448]
This happens when running `aliBuild --defaults o2-daq build O2 --force-unknown-architecture` on current Arch Linux. Boost is at version 1.63 and otherwise working.
Forcing `BOOST_ROOT=/usr` in fairroot.sh works around this issue.

**Comment by dberzano** [comment]
Hi @teo can you check if this is still a problem with the latest iteration of the recipes, and in case open an issue in alidist (not alibuild, which is our build tool?) Thanks!

**Comment by teo** [comment]
This is still a problem. Reopened at https://github.com/alisw/alidist/issues/843.
