### ISSUE TITLE
alienv enter not working on certain MacOS

### ISSUE THREAD

**Issue by sawenzel** [alisw/alibuild#455]
I currently can't use `alienv enter module` on MacOS 10.11.6 preventing me from developing on this platform.

The reason is that entering a fresh shell with `bash -i` (as triggered by alienv) will always unset `LD_LIBRARY_PATH` for security reasons. Hence the environment set up by the modules gets partially erased.

Here is a log of the symptom:
```
macbookprosandrowenzel:~ swenzel$ echo $LD_LIBRARY_PATH

macbookprosandrowenzel:~ swenzel$ export LD_LIBRARY_PATH="Foo"
macbookprosandrowenzel:~ swenzel$ echo $LD_LIBRARY_PATH
Foo
macbookprosandrowenzel:~ swenzel$ bash -i
bash-3.2$ echo $LD_LIBRARY_PATH

bash-3.2$ exit
macbookprosandrowenzel:~ swenzel$ echo $LD_LIBRARY_PATH
Foo
macbookprosandrowenzel:~ swenzel$
```

A more portable workaround might be to enter the new shell first and then set up everything with modules but it requires a few changes in alienv. Or does anyone know of a way to configure bash not unseting this variable?

**Comment by ktf** [comment]
Did sip get reenabled? Can you check with:

```
csrutil status
```
?

**Comment by sawenzel** [comment]
Indeed. Maybe we can check this in alienv and issue a warning message?

**Comment by ktf** [comment]
alibuild checks for that, but admittedly not alienv. May this should be the case (@dberzano to comment on that).

**Comment by dberzano** [comment]
I think it might be worth checking it in alienv indeed.

**Comment by sawenzel** [comment]
@dberzano : @ktf: alibuild did not complain to me about the csrutil thing and compiles everything fine.

**Comment by ktf** [comment]
What command did you invoke? Was `sip-check` part of the build list?

**Comment by dberzano** [comment]
We have indeed `sip-check` but we use it only for fastjet for some reason. In theory, #466 with library relocation should even remove the need for exporting library paths, which is the "proper" way of doing things on macOS. For the moment I would reopen the issue to alidist in order to add the check to other recipes if @sawenzel agrees to close this one.

**Comment by sawenzel** [comment]
Not sure. What speaks against putting the one line check into alienv now? This will quickly fix the problem independently of a later "proper way" but it depends of course on the targeted time-line of these developments.
