### ISSUE TITLE
Feature request: Take Vc from system installation if available

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#459]

**Comment by ktf** [comment]
This is really for `alidist`. Do you have any snippet which allows us to check if vc is the correct one?

**Comment by ktf** [comment]
vc from the system, that is.

**Comment by ktf** [comment]
Did you solve this?

**Comment by davidrohr** [comment]
sorry, forgot about this.
Vc usually installs a cmake FindVc recipe (or how does cmake call this), which exports Vc_VERSION variable.

Otherwise, in include/Vc/version.h there is also the version defined, but the cmake is probably easier.

**Comment by ktf** [comment]
Can you check if https://github.com/alisw/alidist/pull/799 works for you? As I said privately, I've no way to install Vc from the system. In any case let's move the discussion there as this is not really an alibuild issue.
