### ISSUE TITLE
Limit in length of character string

### ISSUE THREAD

**Issue by bovulpes** [alisw/alibuild#462]
Hello,

I am installing on Ubuntu 14.04.5 and the "build" stops at the python installation, the reason being that 
the path 

sw/INSTALLROOT/b1ace07ff674d61efc072e40350b8825fcdfa

does not exist, while there is such a directory but longer by three characters 

sw/INSTALLROOT/b1ace07ff674d61efc072e40350b8825fcdfaa8a

so it is like there is a length limit somewhere which does not include the last three characters of the 
directory path name.

I don't know if this comes from my system.

regards,

Bogdan.

**Comment by ktf** [comment]
Can you tell me what does cut & pasting the following:

```
python << \EOF
import hashlib
print hashlib.sha1("foo").hexdigest()
EOF
```

gives you? Looks like you have a messed up python installation...

-- 
Ciao,
Giulio

**Comment by bovulpes** [comment]
python << \EOF
> import hashlib
> print hashlib.sha1("foo").hexdigest()
> EOF
0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33

**Comment by ktf** [comment]
Ok, it's the same I get. I need to investigate further. Can you provide the full path which is giving you troubles? What filesystem do you use?

**Comment by bovulpes** [comment]
This is the full path and I also attach the full log:

[log.txt](https://github.com/alisw/alibuild/files/1175755/log.txt)

sw/INSTALLROOT/b1ace07ff674d61efc072e40350b8825fcdfaa8a

I have an ext4 file system.

**Comment by ktf** [comment]
I mean the full path before `sw`. Is it long?

**Comment by bovulpes** [comment]
Here it is:

/home/bogdan/Software/O2/sw/INSTALLROOT/b1ace07ff674d61efc072e40350b8825fcdfaa8a

**Comment by bovulpes** [comment]
Moved to a shorter path name and it works (with alibuild 1.5).
Should I close this issue?
