### ISSUE TITLE
aliBuild and aliDoctor disagree on packages to build (Ubuntu 14.04)

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#479]
Hi,

I'm trying to build o2 on Ubuntu 14.04 (in a container, image from travis), and it seems aliDoctor and aliBuild disagree on the packages to be built. Specifically aliBuild wants to build the GCC toolchain (which I'd rather avoid) while aliDoctor says it's ok (see below the tail of the output of both commands). 

GCC 5 (5.4) (including fortran) is installed in $HOME/bin and $HOME/bin is added to PATH.

What stupid mistake am I making ;-) ?

Thanks,

------

\> which gfortran
/home/travis/bin/gfortran

\> travis@442c2165269e:~/build$ ls -l $HOME/bin
total 0
lrwxrwxrwx 1 travis travis 14 Sep  4 09:50 c++ -> /usr/bin/g++-5
lrwxrwxrwx 1 travis travis 14 Sep  4 09:50 cc -> /usr/bin/gcc-5
lrwxrwxrwx 1 travis travis 19 Sep  4 09:50 gfortran -> /usr/bin/gfortran-5

\> aliDoctor O2
... snip...

==> The following packages will be picked up from the system:

    - FreeType
    - Python
    - libxml2
    - SWIG
    - zlib
    - OpenSSL
    - GCC-Toolchain
    - libpng
    - autotools

    If this is not you want, you have to uninstall / unload them.

==> The following packages will be build by aliBuild because they couldn't be picked up from the system:

    - Python-modules
    - Vc
    - CMake
    - protobuf
    - yaml-cpp
    - nanomsg
    - ZeroMQ
    - boost
    - GSL

    This is not a real issue, but it might take longer the first time you invoke aliBuild.

\> aliBuild --dry-run --defaults o2 build O2

==> aliBuild can take the following packages from the system and will not build them:
      Python, libpng, FreeType, autotools

==> The following packages cannot be taken from the system and will be built:
      Python-modules, Vc, CMake, protobuf, GCC-Toolchain, yaml-cpp, nanomsg, ZeroMQ, boost, GSL

==> Packages will be built in the following order:
     - defaults-o2@v1
     - Python-modules@1.0
     - GCC-Toolchain@v6.2.0-alice1
     - boost@v1.64.0-alice1
     - ZeroMQ@v4.1.5
     - CMake@v3.8.2
     - protobuf@v3.0.2
     - GSL@release-1-16
     - Vc@1.3.2
     - pythia6@428-alice1
     - HepMC@alice/v2.06.09
     - DDS@1.7
     - googletest@release-1.8.0
     - yaml-cpp@release-0.5.2
     - nanomsg@c52f1bedca6b72fb31b473929d99f2fe90a13445
     - hijing@v1.36
     - GEANT4@v4.10.01.p03
     - ROOT@v6-10-02
     - lhapdf@v6.1.6
     - vgm@4.3-alice1
     - GEANT3@v2-4
     - pythia@v8223
     - GEANT4_VMC@v3-2-p1-alice1
     - generators@v1.0
     - simulation@v1.0
     - FairRoot@alice-dev-20170711
     - O2@dev

**Comment by Barthelemy** [comment]
Did you set the same defaults when calling aliDoctor ?

**Comment by aphecetche** [comment]
Damn it. Nooooo !

Sure enough with aliDoctor --defaults o2 I get the source of the problem :

> GCC-Toolchain: <stdin>:3:2: error: #error "System's GCC cannot be used: we need at least GCC 6.X. We are going to compile our own version.

Thanks Barth !

**Comment by Barthelemy** [comment]
@ktf @dberzano Shouldn't aliDoctor have complained that O2 requires a defaults ? 
@aphecetche Was your alidist up to date ?

**Comment by ktf** [comment]
@Barthelemy yes, I agree. aliDoctor should have said something about the default.

**Comment by ktf** [comment]
See also #480

**Comment by Barthelemy** [comment]
@ktf thank you for the ticket

**Comment by aphecetche** [comment]
@Barthelemy yes my alidist was up to date ( f60ceb886736b167618fb53f5edb5a3105d07449 Mon Sep 4 11:07:16 2017 +0200)
