### ISSUE TITLE
Incorrect Main package for O2 build depending on the dependency

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#488]
I have a problem that when I add new dependencies to the o2.sh recipe, the main package when invoking aliBuild --defaults o2 O2, is not O2 but it becomes FairRoot. It depends on the dependency that I add. For instance, adding mpfr as dependency triggers the problem, while adding AliRoot does not trigger the problem.
I am using the current master of both alidist and alibuild.

**Comment by davidrohr** [comment]
[with-mpfr.txt](https://github.com/alisw/alibuild/files/1364595/with-mpfr.txt)
[without-mpfr.txt](https://github.com/alisw/alibuild/files/1364594/without-mpfr.txt)
[dist-with-mpfr.pdf](https://github.com/alisw/alibuild/files/1364596/dist-with-mpfr.pdf)
[dist-without-mpfr.pdf](https://github.com/alisw/alibuild/files/1364597/dist-without-mpfr.pdf)

Attached logs of aliBuild --defaults o2 O2 --debug -n for both cases, and the graphs created by 
aliDeps for both cases.

**Comment by davidrohr** [comment]
Hi guys,

so I traced the bug myself. The problem is the case of the dependency.
I.e., putting mpfr as dependency is accepted, but in that case the computation of the build order fails in build.py around line 300, and the build order does not contain the main package O2.
Instead, one has to put the package name inside the recipe, i.e. MPFR instead of mpfr, because the string comparison in the order computation is case sensitive.

I think in order to fix this, the following needs to be changed:
The original check for the dependency which tries to open the .sh file does not check whether the package name defined in the .sh files is equal (case-sensitive) to the required package.

I did not dig further through the aliBuild code because I have a working solution for me now, but I assume you can fix this rather quickly, so other people do not have to spend as much time as I did to find out what is going on.

Cheers
David

**Comment by ktf** [comment]
#490 should have avoided the issue, can you confirm? Let's also continue the discussion there.
