### ISSUE TITLE
AliRoot tests fail on High Sierra

### ISSUE THREAD

**Issue by jniedzie** [alisw/alibuild#494]
Current master of AliRoot compiles and installs correctly on mac os High Sierra, but then most of the tests fails. Full log in the attachment.

[alibuild.log](https://github.com/alisw/alibuild/files/1401106/alibuild.log)

**Comment by ktf** [comment]
Please provide logs as dropbox / cernbox attachments and try to extract the actual cause. This smells like you have some libraries compiled with the old compiler, did you do a full rebuild?

**Comment by jniedzie** [comment]
Today I removed everything, initialised from scratch and recompiled the whole stack. I still have the same problem. I have no clue what can be the cause of this problem, thus I would like to ask for your support.

Can you download the log, or for some reason built-in GitHub attachments don't work properly? For me it works fine...

**Comment by ktf** [comment]
If you are on high sierra, I think you need to compile with `--defaults root6`. @dberzano do you remember the details?

**Comment by syamasak** [comment]
Related issue: https://alice.its.cern.ch/jira/projects/ALIROOT/issues/ALIROOT-7574
We need to fix ROOT5 first...

**Comment by dberzano** [comment]
@jniedzie @syamasak High Sierra/Xcode 9 break ROOT 5 (it builds but it does not work) and neither us nor the ROOT team is going to fix it, so I am sorry to say you need to use ROOT 6 as @ktf correctly pointed out.

For the record: all AliRoot pull requests now have a macOS automatic test running on High Sierra/Xcode 9. So if something is wrong on that side, we will catch the problem. All current tests are green.

@syamasak same story for [ALIROOT-7574](https://alice.its.cern.ch/jira/projects/ALIROOT/issues/ALIROOT-7574): ROOT 5 will not be fixed any more for current and future macOS versions.

**Comment by syamasak** [comment]
@dberzano OK, I prepared SLC 6.9 environment for ROOT 5 and it works fine.
