### ISSUE TITLE
"Prefetching git heads in parallel" fails with no retry

### ISSUE THREAD

**Issue by mconcas** [alisw/alibuild#498]
Probably due to some GitHub-specific setting on concurrent fetches, the 16-threads parallel prefetching step often fails with something like:

<img width="485" alt="screen shot 2017-11-08 at 16 42 49" src="https://user-images.githubusercontent.com/4990252/32558092-440754e0-c4a4-11e7-8551-8ea9393e891f.png">

Would it be possible either to setup an automatic retry or to skip the automatic fetch every time a build is triggered, for example by asking a "`--offline`" mode?

**Comment by dennisklein** [comment]
> ... or to skip the automatic fetch every time a build is triggered, for example by asking a "--offline" mode?

I submitted the `--offline` mode switch just yesterday. Can you please try, if this works for you? See #496.

**Comment by mconcas** [comment]
I tried the `--offline` mode. It is very useful. 
The 16-threads problem indeed still can happen (and it does! :/) on the the first attempt, not relying  on local cache.

**Comment by dennisklein** [comment]
I have discussed the offline feature today with @ktf and we came up with an even better solution than my PR. I will implement it beginning of next week. It should also solve the problem with too big of a thread pool. (Btw, I doubt it is a limitation by github, there should be much more people seeing this problem - but regardless, the new implementation wont need such a large thread pool).
