### ISSUE TITLE
Surprising behaviour of `alienv setenv -c` if using quotes

### ISSUE THREAD

**Issue by olantwin** [alisw/alibuild#510]
Hi,

First of all, thanks for developing `aliBuild`! It's a nice upgrade over what we used before here at SHiP.

I noticed that `alienv setenv -c` as described here 
```
setenv MODULE1[,MODULE2...] -c cmdInEnvironment [PARAM1 [PARAM2...]]
      Executes the given command with environment defined by the given modules.
      Everything after -c is executed as-is.
```

produces surprising results when commands are quoted. A minimal example:

```
> alienv setenv ROOT/latest -c "echo 5"
/home/ol11/.local/bin/alienv: line 275: exec: echo 5: not found
```
vs.
```
> alienv setenv ROOT/latest -c echo 5
5
```

Going back to the documentation it is not obvious what constitutes a `cmdInEnvironment`.  However from experience with similar functionality in other commands, one would expect the results to be the same with and without quotes (and in some cases only the version with quotes works), e.g. the way `bash -c` handles this:

```
> bash -c "echo 5"
5
```

However, if the behaviour described is the intended behaviour,  feel free to ignore this issue.

Please let me know if you need any further information. Unfortunately I do not have time to fix this myself currently, but I'll give it a try when I do.

**Comment by dberzano** [comment]
Hi, this is quite precisely the intended behaviour, and I guess the documentation _is_ crystal clear:

```
-c cmdInEnvironment [PARAM1 [PARAM2...]]
```

meaning: you should provide separate parameters, _without quotes_. This is actually good, because you won't get lost in escaping escapes of escapes of escapes if you see what I mean.

If you want to provide _quoted_ arguments, you can do that by executing a shell with `alienv`, and provide the quoted command line to the shell:

```
alienv setenv WHATEVER/latest -c bash -c "echo 5"
```

Does this clarify?

**Comment by ktf** [comment]
Thank you for your feedback on alibuild, I am glad you like it.

To be fair, I kinda agree with Oliver this is an unfortunate behaviour, as indeed shells do behave differently. However ALICE needs to stay compatible with this for historical reasons, so I am afraid indeed we will not change it as it would complicate too many things.

**Comment by olantwin** [comment]
@dberzano: While the documentation is pretty clear if one looks at it in detail, I fear a lot of people will just assume it will work exactly like the `-c` flag they're familiar with from other commands. 

Not sure how one could make it any clearer though in the documentation, as the problem mostly lies in people thinking they know exactly how it will work.

I certainly agree that not having to perform the quote/escape dance is much nicer than the alternative.

@ktf: I see. While I cannot think of any trivial case right now, there's probably some edge case that would be broken if quotes were stripped/ignored.

**Comment by dberzano** [comment]
Hi @olantwin, you have a point. I am a "convention over configuration" guy so if I know what `bash -c` does, I expect `alienv setenv -c` to carry the same behaviour. The reason why I've implemented it like this is that the original users of aliBuild (ALICE users) were already accustomed to another tool using the implemented syntax. We had that tool in mind, not `bash`. I agree we should clarify the behaviour in the documentation!
