### ISSUE TITLE
"deps" should be able to use "defaults"

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#512]
The "deps" command should understand the "defaults" option because it has an impact on the dependency graph.

**Comment by Barthelemy** [comment]
Are you sure that it is fixed ? 
```
bvonhall@macbookairbarth alice $ aliBuild deps --defaults o2-dataflow O2
usage: aliBuild [-h] [-d] [-n]
                {analytics,architecture,build,clean,deps,doctor,init,version}
                ...
aliBuild: error: unrecognized arguments: --defaults O2
```

**Comment by ktf** [comment]
Looking at the code in:

https://github.com/alisw/alibuild/blob/master/alibuild_helpers/deps.py

it seems it does take into account defaults. Which version are you using?

**Comment by Barthelemy** [comment]
I have just updated it to alibuild-1.5.3 on CC7

**Comment by olantwin** [comment]
Sorry for not specifying, the issue is fixed on master, not yet in the stable version you get from pip.

**Comment by ktf** [comment]
Ah, then we should do a new release. I actually thought this was done a long ago. @dberzano, any showstopper?

**Comment by dberzano** [comment]
Not at all. Actually, I wanted to release the latest RC as stable (we've used it last week with success at the Starterkit), but @olantwin mentioned me some problem, so I kept it on hold. I am closing this ticket and releasing 🎉

**Comment by olantwin** [comment]
The problem I mentioned is #556 , which I don't think is a blocker. Looking forward to the new release!

**Comment by dberzano** [comment]
OK, missed that, sorry. You are right. The release's been done already... will add it to the next I believe.
