### ISSUE TITLE
ERROR:AliPhysics:SWIG:ali-master

### ISSUE THREAD

**Issue by sartozza** [alisw/alibuild#515]
The SWIG test-suite and examples are configured for the following languages:
java perl5 python ruby

+ make -j 4
Dear All,
I have been trying to install Aliphysics on my Mac which runs MacOs High Sierra 10.13.2.
After running:
aliBuild -z -w ../sw -d build AliPhysics
I get the following error:

ERROR:AliPhysics:SWIG:ali-master: Error while executing /Users/Valentina/alice/sw/SPECS/osx_x86-64/SWIG/3.0.7-1/build.sh on `Sartozza.local'.
ERROR:AliPhysics:SWIG:ali-master: Log can be found in /Users/Valentina/alice/sw/BUILD/SWIG-latest/log.
ERROR:AliPhysics:SWIG:ali-master: Please upload it to CernBox/DropBox if you intend to request support.
ERROR:AliPhysics:SWIG:ali-master: Build directory is /Users/Valentina/alice/sw/BUILD/SWIG-latest/SWIG.
Any helpon how to solve it?
Thanks in advance.

Here is the requested part in the log file:
mkdir -p Lib
test -z "" || (cd CCache && /Applications/Xcode.app/Contents/Developer/usr/bin/make)
echo "/* SWIG warning codes */" > Lib/swigwarn.swg
cat Source/Include/swigwarn.h | grep "^#define WARN\|/\*.*\*/\|^[ \t]*$" | sed 's/^#define \(WARN.*[0-9][0-9]*\)\(.*\)$/%define SWIG\1 %enddef\2/' >> Lib/swigwarn.s$
/bin/sh ../Tools/config/ylwrap CParse/parser.y y.tab.c CParse/parser.c y.tab.h `echo CParse/parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/$
../Tools/config/ylwrap: line 174: 85325 Illegal instruction: 4  "$prog" "$@" "$input"
make[1]: *** [CParse/parser.c] Error 132
make: *** [source] Error 2

**Comment by ktf** [comment]
Assuming this was fixed. Cannot reproduce.
