### ISSUE TITLE
403 Forbidden when downloading from geant4.cern.ch

### ISSUE THREAD

**Issue by hrzhao76** [alisw/alibuild#520]
I'm using alibuild to configure aliphysics, but I come across problems. 
Here is the log:

+ cmake /Users/haoran/alice/sw/SOURCES/GEANT4/v4.10.01.p03-alice1/v4.10.01.p03-alice1 -DGEANT4_INSTALL_DATA_TIMEOUT=1500 -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_INSTALL_PREFIX:PATH=/Users/haoran/alice/sw/INSTALLROOT/bae9dcd91f33e1a9c3c478492e383467b6d234f0/osx_x86-64/GEANT4/v4.10.01.p03-alice1-1 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEANT4_BUILD_TLS_MODEL:STRING=global-dynamic -DGEANT4_ENABLE_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DGEANT4_INSTALL_EXAMPLES=OFF -DCLHEP_ROOT_DIR:PATH= -DGEANT4_BUILD_MULTITHREADED=OFF -DCMAKE_STATIC_LIBRARY_CXX_FLAGS=-fPIC -DCMAKE_STATIC_LIBRARY_C_FLAGS=-fPIC -DGEANT4_USE_G3TOG4=ON -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_SYSTEM_EXPAT=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Configuring download of missing dataset G4NDL (4.5)
-- Configuring download of missing dataset G4EMLOW (6.41)
-- Configuring download of missing dataset PhotonEvaporation (3.1)
-- Configuring download of missing dataset RadioactiveDecay (4.2)
-- Configuring download of missing dataset G4NEUTRONXS (1.4)
-- Configuring download of missing dataset G4PII (1.3)
-- Configuring download of missing dataset RealSurface (1.0)
-- Configuring download of missing dataset G4SAIDDATA (1.1)
-- Configuring download of missing dataset G4ABLA (3.0)
-- Configuring download of missing dataset G4ENSDFSTATE (1.0)
-- The following Geant4 features are enabled:
GEANT4_BUILD_CXXSTD: Compiling against C++ Standard 'c++98'
GEANT4_USE_G3TOG4: Building Geant3 ASCII call list reader library

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_STATIC_LIBRARY_CXX_FLAGS
    CMAKE_STATIC_LIBRARY_C_FLAGS
    GEANT4_INSTALL_EXAMPLES

-- Build files have been written to: /Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4
+ make -j 4
Scanning dependencies of target G4ABLA
Scanning dependencies of target G4PII
Scanning dependencies of target G4ENSDFSTATE
Scanning dependencies of target G4SAIDDATA
[  0%] Creating directories for 'G4SAIDDATA'
[  0%] Creating directories for 'G4ABLA'
[  0%] Creating directories for 'G4ENSDFSTATE'
[  0%] Creating directories for 'G4PII'
[  0%] Performing download step (download, verify and extract) for 'G4ENSDFSTATE'
[  0%] Performing download step (download, verify and extract) for 'G4ABLA'
[  0%] Performing download step (download, verify and extract) for 'G4SAIDDATA'
[  0%] Performing download step (download, verify and extract) for 'G4PII'
-- downloading...
     src='http://geant4.cern.ch/support/source/G4ENSDFSTATE.1.0.tar.gz'
     dst='/Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4ENSDFSTATE-1.0/src/G4ENSDFSTATE.1.0.tar.gz'
     timeout='1500 seconds'
-- downloading...
     src='http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz'
     dst='/Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4ABLA-3.0/src/G4ABLA.3.0.tar.gz'
     timeout='1500 seconds'
-- downloading...
     src='http://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz'
     dst='/Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4SAIDDATA-1.1/src/G4SAIDDATA.1.1.tar.gz'
     timeout='1500 seconds'
-- downloading...
     src='http://geant4.cern.ch/support/source/G4PII.1.3.tar.gz'
     dst='/Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4PII-1.3/src/G4PII.1.3.tar.gz'
     timeout='1500 seconds'
CMake Error at /Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4SAIDDATA-1.1/src/G4SAIDDATA-stamp/download-G4SAIDDATA.cmake:27 (message):
  error: downloading
  'http://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz' failed

    status_code: 22
    status_string: "HTTP response code said error"
    log:   Trying 188.184.163.48...

  Connected to geant4.cern.ch (188.184.163.48) port 80 (#0)

  GET /support/source/G4SAIDDATA.1.1.tar.gz HTTP/1.1

  Host: geant4.cern.ch

  User-Agent: curl/7.44.0

  Accept: */*

  

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

make[2]: *** [Externals/G4SAIDDATA-1.1/src/G4SAIDDATA-stamp/G4SAIDDATA-download] Error 1
make[1]: *** [CMakeFiles/G4SAIDDATA.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at /Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4ABLA-3.0/src/G4ABLA-stamp/download-G4ABLA.cmake:27 (message):
  error: downloading 'http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz'
  failed

    status_code: 22
    status_string: "HTTP response code said error"
    log:   Trying 188.184.163.48...

  Connected to geant4.cern.ch (188.184.163.48) port 80 (#0)

  GET /support/source/G4ABLA.3.0.tar.gz HTTP/1.1

  Host: geant4.cern.ch

  User-Agent: curl/7.44.0

  Accept: */*

  

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

CMake Error at /Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4ENSDFSTATE-1.0/src/G4ENSDFSTATE-stamp/download-G4ENSDFSTATE.cmake:27 (message):
  error: downloading
  'http://geant4.cern.ch/support/source/G4ENSDFSTATE.1.0.tar.gz' failed

    status_code: 22
    status_string: "HTTP response code said error"
    log:   Trying 188.184.163.48...

  Connected to geant4.cern.ch (188.184.163.48) port 80 (#0)

  GET /support/source/G4ENSDFSTATE.1.0.tar.gz HTTP/1.1

  Host: geant4.cern.ch

  User-Agent: curl/7.44.0

  Accept: */*

  

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

make[2]: *** [Externals/G4ABLA-3.0/src/G4ABLA-stamp/G4ABLA-download] Error 1
make[1]: *** [CMakeFiles/G4ABLA.dir/all] Error 2
make[2]: *** [Externals/G4ENSDFSTATE-1.0/src/G4ENSDFSTATE-stamp/G4ENSDFSTATE-download] Error 1
make[1]: *** [CMakeFiles/G4ENSDFSTATE.dir/all] Error 2
CMake Error at /Users/haoran/alice/sw/BUILD/bae9dcd91f33e1a9c3c478492e383467b6d234f0/GEANT4/Externals/G4PII-1.3/src/G4PII-stamp/download-G4PII.cmake:27 (message):
  error: downloading 'http://geant4.cern.ch/support/source/G4PII.1.3.tar.gz'
  failed

    status_code: 22
    status_string: "HTTP response code said error"
    log:   Trying 188.184.163.48...

  Connected to geant4.cern.ch (188.184.163.48) port 80 (#0)

  GET /support/source/G4PII.1.3.tar.gz HTTP/1.1

  Host: geant4.cern.ch

  User-Agent: curl/7.44.0

  Accept: */*

  

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

make[2]: *** [Externals/G4PII-1.3/src/G4PII-stamp/G4PII-download] Error 1
make[1]: *** [CMakeFiles/G4PII.dir/all] Error 2
make: *** [all] Error 2

**Comment by ktf** [comment]
This is an upstream problem with the geant4 web site. I contacted the admin and it should be hopefully solved. Can you try again? Please feel free to reopen if this is not the case.
