### ISSUE TITLE
alibuild is trying to close github issues, but does not seem to work

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alibuild#525]
Issue https://github.com/AliceO2Group/AliceO2/issues/921 was created by alibuild, and it also tried to close it according to the message, but still needs to be closed manually..

**Comment by brinick** [comment]
Not surprised, the code doing the HTTP PATCH to close the issue
is using the wrong URL...I'll fix this now.

**Comment by brinick** [comment]
Fixed in alisw/ali-bot#553

**Comment by matthiasrichter** [comment]
Hi @brinick , thanks a lot, there seems to be another corner case https://github.com/AliceO2Group/AliceO2/issues/942 , where the bot did not succeed to close just a few hours ago.
