### ISSUE TITLE
Build in SOURCEDIR

### ISSUE THREAD

**Issue by qgp** [alisw/alibuild#53]
For packages which are built in-source, the build directory is the same across architectures.

Proposal: cp/rsync SOURCEDIR to BUILDDIR and do configure, make, make install from there

**Comment by ktf** [comment]
That's correct. In that case one should do:

```
rsync -a $SOURCEDIR/ ./
```

in the recipe itself. This is what is done in a few places, but admittedly not everywhere.

Do you have a list of recipes which behave this way?

**Comment by qgp** [comment]
At the moment, I see this for pythia8, lhapdf, and thepeg. I am anyway working on thepeg to make it work. Will you do it for the others or should I put it in since I'm anyway testing?

**Comment by ktf** [comment]
If you can do it, that would be great!

**Comment by qgp** [comment]
Done, see pull request #65 in alidist. Closing this issue.

**Comment by ktf** [comment]
For the record, you can use alisw/alidist#65 to refer to a pull request in a different repository. Thanks. Merged.
