### ISSUE TITLE
alibuild_helpers.utilities.prunePaths undefines essential Cray PE environment variables

### ISSUE THREAD

**Issue by yslai** [alisw/alibuild#530]
Running `aliBuild build` on Cray XC40, with Cray PE installed, fails with missing packages that are however properly installed. And interestingly, `aliBuild doctor` is able to successfully pick up those packages. Porting the diagnostic code from `alibuild_helpers.doctor` into `alibuild_helpers.build` reveals that the failure is (and similarly, for `Xdevel`, `curl`, and `libperl`):

```
ERROR: Package opengl is a system requirement and cannot be found.
ERROR: This is due to the fact that the following script fails:
ERROR: 
ERROR: brew() { true; }; printf "#include <GL/glu.h>\n" | cc -xc - -c -o /dev/null
ERROR: with the following output:
ERROR: 
ERROR: opengl: Error:
ERROR: opengl: Unable to determine compiler version.
ERROR: opengl: Make sure that a gnu module is loaded and that GNU_VERSION is defined
ERROR: opengl: 
ERROR: OpenGL development packages are missing on your system.
ERROR:   * On RHEL-compatible systems you probably need: mesa-libGLU-devel
ERROR:   * On Ubuntu-compatible systems you probably need: libglu1-mesa-dev
ERROR: 
ERROR: 
```
It turns out only `alibuild_helpers.build.doBuild` additionally calls `alibuild_helpers.utilities.prunePaths`, which clears any environment variable ending in `_VERSION` (with the `ALIBUILD_VERSION` as exception), that also unsets various `*_VERSION` that the Cray PE needs to function:

```
CRAYPE_VERSION
CRAY_LIBSCI_VERSION
DVS_VERSION
GCC_VERSION
GNU_VERSION
INTEL_MAJOR_VERSION
INTEL_MINOR_VERSION
INTEL_VERSION
LIBSCI_VERSION
```

**Comment by ktf** [comment]
Interesting.. We rely on the same variables to communicate the version of alibuild built packages, hence why we clean them up... We admittedly could use a less generic pattern, however that would not be something we can do quickly. For the moment I suggest you simply comment out `alibuild_helpers.utilities.prunePaths` call and hope for the best. We could actually think of a switch to "trust environment"...

@dberzano

**Comment by dberzano** [comment]
I think my PR fixes it.
