### ISSUE TITLE
init.sh script contains wrong paths on cvmfs (nightly) installs

### ISSUE THREAD

**Issue by sawenzel** [alisw/alibuild#539]
Trying to source the `init.sh` file for O2 in the cvmfs-nightlies fails.

The script I am trying to source is 

`/cvmfs/alice-nightlies.cern.ch/el7-x86_64/Packages/O2/nightly-20180503-1/etc/profile.d/init.sh`

This fails mostly because the `init.sh` refers to other paths mentioning `slc7-x86_64` instead of `el7-x86_64` and does not follow the directory convention ../Packages/FOO/... used on cvmfs.

**Comment by ktf** [comment]
Agreed that something is wrong with the relocation on CVMFS (which is not done by alibuild, but that's a detail). We should fix that.

**Comment by ktf** [comment]
This is now fixed.
