### ISSUE TITLE
build AliRoot doesn't work in ubuntu 18.04

### ISSUE THREAD

**Issue by bdrum** [alisw/alibuild#541]
Hello @dberzano!

I updated my ubuntu to the last version and I couldn't build AliRoot. I'm not sure in fundamentals of my solutions, but it was:
1. Change automake-1.15 to automake-1.15.1 ( I just moved source folder).
2. In sw/SOURCES/autotools/v1.4.0/v1.4.0/pkg-config-0.29/glib/glib/gdate.c 
 I added 
![image](https://user-images.githubusercontent.com/16210997/40908579-e19864c6-67ef-11e8-9ee7-11e10d775631.png)

After it, build was fine for root6 and root5. 

I hope, it will save your time when you will be prepare the project for latest version of ubuntu.

Cheers,
Boris

**Comment by dberzano** [comment]
Hi, are you aware of [our instructions](https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html)? You don't need to build automake on Ubuntu as it comes as a system package. If you have a problem with a recipe, please open a PR/issue to:

> https://github.com/alisw/alidist/

If you have a problem with the aforementioned documentation, same thing with:

> https://github.com/alice-doc/alice-analysis-tutorial/

Cheers

**Comment by bdrum** [comment]
> You don't need to build automake on Ubuntu as it comes as a system package
Glad to hear it.

I used this tutorial:
https://alice-doc.github.io/alice-analysis-tutorial/building/
Anyway, all what I wanted to say, that 
```bash
aliBuild build AliRoot --defaults user
```
Doesn't work for ubuntu 18.04. 
So ok, I just close this issue, thanks.
Boris
