### ISSUE TITLE
Re-eval "`alienv shell-helper`" needed for proper loading the environment

### ISSUE THREAD

**Issue by vpacik** [alisw/alibuild#549]
When opening a new terminal, ```alienv``` is not found 
```
Last login: Fri Aug 10 10:58:11 on ttys000
-bash: alienv: command not found
```
even though the shell-helper is evaluated (as seen from ~/.bash_profile)
```
export ALIBUILD_WORK_DIR="$HOME/alice/sw"
eval "`alienv shell-helper`"
```

Moreover, loading an enviroment fails with following message (see [full output](https://github.com/alisw/alibuild/files/2277303/alienv_load_out.txt))
```
vpacik@dhcp0ad: ~ $ alienv load AliPhysics/latest
Use alienv list to list loaded modules.
ALICE=/Users/vpacik/alice/sw/osx_x86-64/AliRoot ;export 
[...]
VC_ROOT;X509_CERT_DIR=/Users/vpacik/alice/sw/osx_x86-64/AliEn-Runtime/v2-19-le-1/globus/share/certificates ;export X509_CERT_DIR;_LMFILES_=/Users/vpacik/alice/sw/MODULES/osx_x86-64/BASE/1.0:/Users/vpacik/alice/sw/MODULES/osx_x86-64/AliEn-Runtime/v2-19-le-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/GSL/v1.16-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/ROOT/v6-10-08-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/cgal/v4.6.3-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/fastjet/v3.2.1_1.024-alice3-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/Vc/1.3.3-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/AliRoot/Root-6-10-1:/Users/vpacik/alice/sw/MODULES/osx_x86-64/AliPhysics/latest ;export
_LMFILES_;unset ;
```
After some testing, it seems that  re-```eval``` of shell-helper (or ```source ~/.bash_profile```) remedy the situation and the environment is successfully loaded.

NB: ```alienv enter AliPhysics/latest``` is not affected by this and it can be successfully done directly from fresh terminal.

Do you have any idea/suggestions what could go wrong?

**Comment by dberzano** [comment]
Hi @vpacik, let's have a look at how bash loads its configuration files.

* `~/.bash_profile` is loaded for login shells
* `~/.bashrc` is loaded for non-login shells

This distinction does not make much sense any more today; on Linuxes, new terminal windows normally load `~/.bashrc`, but on Macs `~/.bash_profile` is loaded.

Linux TTYs and SSH use `~/.bash_profile`. Starting `bash` from within an existing terminal invokes `~/.bashrc`.

In practice the situation is so convoluted that most users have the full configuration inside `~/.bashrc` and have `~/.bash_profile` simply loading `~/.bashrc`:

```bash
[[ -e $HOME/.bashrc ]] && source $HOME/.bashrc
```

In your case, `~/.bash_profile` is simply not used, therefore the shell helper is not loaded. I suggest you do the above, and put the whole `shell-helper` stuff inside `~/.bashrc`.

**Comment by vpacik** [comment]
Hi @dberzano,

Unfortunately, this did not solved the issue, but knowing what to look for and after some digging through stack-overflow I realised that the issue actually lies in my $PATH (somehow python/conda related).

Thank you very much for your reply and pointing me to proper direction!
