### ISSUE TITLE
Wrong boost version is installed?

### ISSUE THREAD

**Issue by KlewinS** [alisw/alibuild#559]
alibuild failed to compile DDS because the wrong boost version is found:

DEBUG:O2:DDS:0: CMake Error at /Users/Sebastian/alice/sw/osx_x86-64/CMake/v3.13.1-1/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
DEBUG:O2:DDS:0:   Unable to find the requested Boost libraries.
DEBUG:O2:DDS:0: 
DEBUG:O2:DDS:0:   Boost version: 1.66.0
DEBUG:O2:DDS:0: 
DEBUG:O2:DDS:0:   Boost include path:
DEBUG:O2:DDS:0:   /Users/Sebastian/alice/sw/osx_x86-64/boost/v1.68.0-1/include
DEBUG:O2:DDS:0: 
DEBUG:O2:DDS:0:   Detected version of Boost is too old.  Requested version was 1.67 (or
DEBUG:O2:DDS:0:   newer).

I checked the file 
/Users/Sebastian/alice/sw/osx_x86-64/boost/v1.68.0-1/include/boost/version.hpp 

which defines the boost version as 1.66
#define BOOST_LIB_VERSION "1_66"  

although the file is located in the directory for 1.68

The same is true in the SOURCE directory, also file 
 /Users/Sebastian/alice/sw/SOURCES/boost/v1.68.0/v1.68.0/boost/version.hpp 
defines the version of boost to be 1.66

Is this a problem only on my machine or a general aliBuild problem with boost? my alidist is on the most recent master branch.

**Comment by ktf** [comment]
Do you use boost as a development package?

**Comment by KlewinS** [comment]
no
