### ISSUE TITLE
Compilation of DDS fails on MacOSX

### ISSUE THREAD

**Issue by KlewinS** [alisw/alibuild#560]
The build of DDS fails both, standalone and in the sequence of compilations for O2:
```
aliBuild build DDS --defaults o2
aliBuild build O2 --defaults o2
```
because libicudata.63.1.dylib can not be found in both cases.

O2 is only package in development mode.

[log.txt](https://github.com/alisw/alibuild/files/2763506/log.txt)

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/1467 works around the problem. Closing this.
