### ISSUE TITLE
Control-Core build crashes on macOS

### ISSUE THREAD

**Issue by kostorr** [alisw/alibuild#563]
[control-core-mac.log](https://github.com/alisw/alibuild/files/3140825/control-core-mac.log)

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/1615 fixes the issue. Thanks for spotting this.

**Comment by teo** [comment]
@ktf the recipe obviously had bad input, but shouldn't this be fixed in aliBuild?

**Comment by ktf** [comment]
Yes, working on it.

**Comment by ktf** [comment]
https://github.com/alisw/alibuild/pull/565
