### ISSUE TITLE
Add support for another SCM ? (E.g. mercurial)

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#566]
How much aliBuild is tied to Git ? How much work would it be to make it able to grab sources from other(s) SCM ?

Use case below, in case it’s doable.

Thanks,

—-

Case in point : mercurial. Not because I like it (nor I know how to use it ;-) ) but because, for instance,  LHAPDF is handled with it. We do have a copy of that repository in github, but as far as I can tell, we have no modification whatsoever there, so I assume the only reason is git vs hg, which is already not so nice.

Besides, if I want to make a fix in LHAPDF (and get the fix in our Alice builds) I have to either : 

1 - patch our git mirror right away (and maybe forget to contribute back this fix to the project)
2 - contribute the fix back to the project, wait for it to be intregrated, and then resync our mirror.

1 is of course faster, but 2 would be much better in the long term (and would be easier by just using the tools of that project)

**Comment by ktf** [comment]
The decision at the time was to only integrate with git and manage other sources with ad-hoc solutions. This allows us to keep things simple and have fast incremental builds. The rationale being that cumulative overhead of doing 1. 2. for the next 10 years is probably less than the effort which would be required to support multiple backends. At the moment I would personally keep it as it is and live with the occasional overhead. So it's not git vs. hg, but merely a support 99% of the packages patching activities vs 1%.

**Comment by ktf** [comment]
Ciao, I've added a DESIGN.md document with the explanation, so I am closing this issue as "won't fix". Of course we might reconsider it in the future, but for the moment it stays like this.

**Comment by ktf** [comment]
#567
