### ISSUE TITLE
ERROR while updating reference repos 

### ISSUE THREAD

**Issue by vaibhavlohiya** [alisw/alibuild#569]
I'm having a problem after I type in my CERN username and password

Username for 'https://gitlab.cern.ch': vaibhav.lohia@cern.ch
Password for 'https://vaibhav.lohia@cern.ch@gitlab.cern.ch': 
fatal: Authentication failed for 'https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git/'
DEBUG: 
ERROR: Error while updating reference repos https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git.

also, it is showing me alibuild as an invalid command when I'm trying to install AliPhysics

vaibhav@vaibhav-HP-Pavilion-Notebook:~/alidock$ aliBuild init AliPhysics@master
aliBuild: command not found

I'm using Ubuntu 16.04 LTS

**Comment by ktf** [comment]
I missed this. Is this still relevant? You need to be member of the alice-member mailing list in order to be able to get DPMJET. If you do not need it, simply disable it with `--disable DPMJET`.
