### ISSUE TITLE
Printout package currently being built.

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#57]
Right now alibuild uses the following format for debug output:

```
DEBUG:<package>:<hash>: <output from the build>
```

Where package is the final package being built. It would be great if we could add an additional bit where the current package being built is show, e.g.:

```
DEBUG:<package>:<hash>:<current-package>: <output from the build>
```

Doing this requires:
- [ ] Trivial change in alibuild.
- [ ] Change https://github.com/alisw/ali-bot/blob/master/logstash/logstash.conf to parse the new bit and put it in a new field.
- [ ] Change the elasticsearch schema to avoid having the field being analysed.
- [ ] Deploy the new elasticsearch schema.
- [ ] Restart logstash instance in marathon so that the new configuration is picked up.

**Comment by dberzano** [comment]
Fixed in #473.
