### ISSUE TITLE
f{29,30} :: alienv no longer see the dependency chain

### ISSUE THREAD

**Issue by adriansev** [alisw/alibuild#572]
Hi! it seems that in fedora 29 and 30 something changed that make the alienv not be able to load dependency chain. If the dependency chain is manually expressed then the enter/load work.   
`alienv load AliPhysics/ali-latest-r6-next-1
Use alienv list to list loaded modules.
Loading AliRoot/ali-latest-r6-next-1
  ERROR: AliRoot/ali-latest-r6-next-1 cannot be loaded due to missing prereq.
    HINT: the following module must be loaded first: ROOT/v6-16-00-1

Loading RooUnfold/V02-00-01-alice4-1
  ERROR: RooUnfold/V02-00-01-alice4-1 cannot be loaded due to missing prereq.
    HINT: the following module must be loaded first: ROOT/v6-16-00-1

Loading AliPhysics/ali-latest-r6-next-1
  ERROR: Load of requirement AliRoot/ali-latest-r6-next-1 failed`   

`alienv enter BASE/1.0,AliEn-Runtime/v2-19-le-3,Python-modules/1.0-1,ROOT/v6-16-00-1,AliEn-ROOT-Legacy/0.0.7-1,Vc/1.4.1-1,boost/v1.68.0-2,cgal/v4.6.3-2,fastjet/v3.2.1_1.024-alice3-2,AliRoot/ali-latest-r6-next-1,RooUnfold/V02-00-01-alice4-1,treelite/2a12742269-1,AliPhysics/ali-latest-r6-next-1
Currently Loaded Modulefiles:
 1) BASE/1.0                   3) Python-modules/1.0-1   5) AliEn-ROOT-Legacy/0.0.7-1   7) boost/v1.68.0-2   9) fastjet/v3.2.1_1.024-alice3-2  11) RooUnfold/V02-00-01-alice4-1  13) AliPhysics/ali-latest-r6-next-1  
 2) AliEn-Runtime/v2-19-le-3   4) ROOT/v6-16-00-1        6) Vc/1.4.1-1                  8) cgal/v4.6.3-2    10) AliRoot/ali-latest-r6-next-1   12) treelite/2a12742269-1         
Use alienv list to list loaded modules. Use exit to exit this environment.
[BASE/1.0 AliEn-Runtime/v2-19-le-3 Python-modules/1.0-1 ROOT/v6-16-00-1 AliEn-ROOT-Legacy/0.0.7-1 Vc/1.4.1-1 boost/v1.68.0-2 cgal/v4.6.3-2 fastjet/v3.2.1_1.024-alice3-2 AliRoot/ali-latest-r6-next-1 RooUnfold/V02-00-01-alice4-1 treelite/2a12742269-1 AliPhysics/ali-latest-r6-next-1] ~ $> exit`

**Comment by olantwin** [comment]
Do you have `environment-modules-compat` installed?

I think installing it solved the issue in my case (Fedora 30).

**Comment by adriansev** [comment]
yes, both `environment-modules` and `environment-modules-compat` are installed

**Comment by olantwin** [comment]
Could you try setting `MODULES_AUTO_HANDLING=1`?

**Comment by adriansev** [comment]
@olantwin It works!!!! this was it! Thanks a lot!!
