### ISSUE TITLE
Add option to force the rebuild of a package

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#573]
For some reasons, e.g. recreating the logs or making sure that a package is built against the current system installation, I want to be able to force the rebuild of a package. 

At the moment I have to delete everything related to this package to make aliBuild rebuild it. I would like an option like : 
`aliBuild build --defaults o2 --force-rebuild root QualityControl`

This option can appear several times or should accept a list of packages.

**Comment by ktf** [comment]
I can add the option, but what it will probably do is to simply remove the associated BUILD folder and rebuild. Would that be ok?

**Comment by Barthelemy** [comment]
That would be fine. I thought that more folders/files needed to be removed in order to trigger a rebuild. Typically, the install directory has to be removed to force the rebuild in my experience.

**Comment by ktf** [comment]
Correct, actually.

**Comment by ktf** [comment]
https://github.com/alisw/alibuild/pulls should probably address this request. Closing it.
