### ISSUE TITLE
Release for Python3

### ISSUE THREAD

**Issue by siscia** [alisw/alibuild#577]
It seems like aliBuild, if installed through `pip` works only with python2.

The code seems to support python3. It is possible to have a release with Python3 compatible setup.py file?

**Comment by ktf** [comment]
Weird, in principle it should work with both. I will take a look.

**Comment by ktf** [comment]
Are you sure you are using pip3 rather than pip? It works for me...

**Comment by siscia** [comment]
Figured it out.

I got a shebang with python2 in my files.
Most likely is because was installed with pip.

This was preventing it to run in a python3 installation directory.
