### ISSUE TITLE
Feature Request: Open a build shell

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#584]
Running make in the build directory differs from running `aliBuild build` in the environment, so the result is not always the same / the expected one.

E.g. I do the following:
- `aliBuild build O2` : full build of O2.
- minor change + `aliBuild buld O2` : incremental rebuild works, rebuilds only what was changed.
- minor change + `cd sw/BUILD/O2-latest/O2 && make` : Builds O2, but it rebuilds all files. I think this is because the environment is different, so cmake changes something in compile/link flags, and thus must rebuild all files.
- minor change + `make` (again in build folder): works as expected, rebuilds only what was changed.
- minor change + `aliBuild build O2` : uses the incremental recipe correctly, but again rebuilds all files, since something in the environment has changed.

I propose a command like `aliBuild --defaults o2 shell O2`, which gives me a shell in the build directory with exactly the environment that is used by aliBuild during `aliBuild build`.

**Comment by ktf** [comment]
With 1.5.5, you can already do that if you install [direnv](https://direnv.net) and then you cd in the build folder of a given package. In that way you should have exactly the same build environment as the one used by alibuild.

**Comment by davidrohr** [comment]
ok, thx, that seems to be what I want. But isn't that possible without messing with my shell, by simply sourcing a file? If I don't miss something, it should be simply possible to source the `.envrc`, which will source in my O2 case `WORK_DIR=/home/qon/alice/sw source ../../../gentoo2_x86-64/O2/1.0.0-1/etc/profile.d/init.sh`, which will set up everything.
I guess the error about source_up can be ignored, if I don't have `direnv`.

**Comment by davidrohr** [comment]
OK, I tried that and it seems to work. thx a lot.

**Comment by ktf** [comment]
Yes, `WORK_DIR=/home/qon/alice/sw source ../../../gentoo2_x86-64/O2/1.0.0-1/etc/profile.d/init.sh` also would work. Just more typing.
