### ISSUE TITLE
CMake failing to build HepMC3@3.2.2 on alidock from aliBuild build AliGenerators

### ISSUE THREAD

**Issue by Nikolajal** [alisw/alibuild#631]
==> Building HepMC3@3.2.2
==> HepMC3 is being built (use --debug for full output): failed    
ERROR: Error while executing /persist/sw/SPECS/slc7_x86-64/HepMC3/3.2.2-1/build.sh on `alidock-501'.
ERROR: Log can be found in /persist/sw/BUILD/HepMC3-latest/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is /persist/sw/BUILD/HepMC3-latest/HepMC3.

Log:
[ 80%] Built target HepMC3
make  -f search/CMakeFiles/HepMC3search.dir/build.make search/CMakeFiles/HepMC3search.dir/depend
make  -f rootIO/CMakeFiles/HepMC3rootIO.dir/build.make rootIO/CMakeFiles/HepMC3rootIO.dir/depend
make[2]: Entering directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
cd /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3 && /persist/sw/slc7_x86-64/CMake/v3.18.2-2/bin/cmake -E cmake_depends "Unix Makefiles" /persist/sw/SOURCES/HepMC3/3.2.2/3.2.2 /persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3 /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/search /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/search/CMakeFiles/HepMC3search.dir/DependInfo.cmake --color=
make[2]: Entering directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
make[2]: *** No rule to make target `/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/rootIO/NOINSTALL', needed by `rootIO/G__HepMC3rootIO.cxx'.  Stop.
make[2]: Leaving directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
make[1]: *** [rootIO/CMakeFiles/HepMC3rootIO.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target HepMC3search
make[2]: Leaving directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
make  -f search/CMakeFiles/HepMC3search.dir/build.make search/CMakeFiles/HepMC3search.dir/build
make[2]: Entering directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
[ 82%] Building CXX object search/CMakeFiles/HepMC3search.dir/src/Relatives.cc.o
cd /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/search && /persist/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-2/bin/c++ -DHEPMC3_ROOTIO -DHepMC3search_EXPORTS -I/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search -I/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/include -I/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/include -I/persist/sw/slc7_x86-64/ROOT/v5-34-30-alice10-2/include -fPIC -g -O2 -std=c++11 -std=c++11 -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations -O2 -DNDEBUG -fPIC -o CMakeFiles/HepMC3search.dir/src/Relatives.cc.o -c /persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/src/Relatives.cc
[ 83%] Building CXX object search/CMakeFiles/HepMC3search.dir/src/Selector.cc.o
cd /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/search && /persist/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-2/bin/c++ -DHEPMC3_ROOTIO -DHepMC3search_EXPORTS -I/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search -I/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/include -I/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/include -I/persist/sw/slc7_x86-64/ROOT/v5-34-30-alice10-2/include -fPIC -g -O2 -std=c++11 -std=c++11 -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations -O2 -DNDEBUG -fPIC -o CMakeFiles/HepMC3search.dir/src/Selector.cc.o -c /persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/src/Selector.cc
In file included from /persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/include/HepMC3/Selector.h:13:0,
                 from /persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/src/Selector.cc:10:
/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/include/HepMC3/Filter.h: In function 'bool HepMC3::ACCEPT_ALL(HepMC3::ConstGenParticlePtr)':
/persist/sw/SOURCES/HepMC3/3.2.2/3.2.2/search/include/HepMC3/Filter.h:41:44: warning: unused parameter 'dummy' [-Wunused-parameter]
 inline bool ACCEPT_ALL(ConstGenParticlePtr dummy) {
                                            ^~~~~
[ 85%] Linking CXX shared library ../outputs/lib/libHepMC3search.so
cd /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/search && /persist/sw/slc7_x86-64/CMake/v3.18.2-2/bin/cmake -E cmake_link_script CMakeFiles/HepMC3search.dir/link.txt --verbose=1
/persist/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-2/bin/c++ -fPIC -fPIC -g -O2 -std=c++11 -std=c++11 -pipe -m64 -Wall -W -Woverloaded-virtual -fPIC -pthread -std=c++11 -Wno-deprecated-declarations -O2 -DNDEBUG  -Wl,--no-undefined -shared -Wl,-soname,libHepMC3search.so.4 -o ../outputs/lib/libHepMC3search.so.4 CMakeFiles/HepMC3search.dir/src/Relatives.cc.o CMakeFiles/HepMC3search.dir/src/Selector.cc.o  -Wl,-rpath,/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/outputs/lib:::::::::::::::::: ../outputs/lib/libHepMC3.so.3 
cd /persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3/search && /persist/sw/slc7_x86-64/CMake/v3.18.2-2/bin/cmake -E cmake_symlink_library ../outputs/lib/libHepMC3search.so.4 ../outputs/lib/libHepMC3search.so.4 ../outputs/lib/libHepMC3search.so
make[2]: Leaving directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
[ 85%] Built target HepMC3search
make[1]: Leaving directory `/persist/sw/BUILD/476bbea6a3356e0077b08934db23052293f63f44/HepMC3'
make: *** [all] Error 2

**Comment by mconcas** [comment]
Hello, installation using alidock has been deprecated. Please use the official installation method: https://alice-doc.github.io/alice-analysis-tutorial/building/custom.html

Regards
