### ISSUE TITLE
Building ROOT@v5-34-30-alice10

### ISSUE THREAD

**Issue by ameermukhtar81** [alisw/alibuild#636]
==> ROOT is being built (use --debug for full output): failed    
ERROR: Error while executing /home/ameer/alice/sw/SPECS/ubuntu2004_x86-64/ROOT/v5-34-30-alice10-1/build.sh on `ameer-Latitude-E6440'.
ERROR: Log can be found in /home/ameer/alice/sw/BUILD/ROOT-latest/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is /home/ameer/alice/sw/BUILD/ROOT-latest/ROOT.
Sir please guide me how to solve this?
Cheers
Ameer Mukhtar

**Comment by ktf** [comment]
I assume this was fixed? Closing. Please provide at least the log, otherwise. Most likely you want to use the next-root6 default I guess.
