### ISSUE TITLE
Depend on specific version

### ISSUE THREAD

**Issue by qgp** [alisw/alibuild#64]
It seems we need LHAPDF 5.x for ThePEG since some PDFsets are not available in v6.x. What's the idea to have multiple versions installaed and pulled in as dependency? In a way, LHAPDF 5 and 6 are similar to pythia6 and pythia8, which simply got different package names.

**Comment by ktf** [comment]
Can't you just download the new PDF sets? IIRC they pruned a few of them.

**Comment by qgp** [comment]
That's what I tried, of course. Maybe I have overlooked something, but with LHAPDF 6 I can't get cteq6l; there is cteq6l1 which I can download and install, but this doesn't make ThePEG happy. Or are you suggesting to download the PDFset for LHAPDF 5 and stuff it into LHAPDF 6?

**Comment by ktf** [comment]
I would call them LHAPDF5 and LHAPDF. You should sync with @dberzano though, as I know he is looking in something related to LHAPDF as well.

**Comment by ktf** [comment]
Closing this as the solution for this is already in alibuild / alidist:

- In case you want to run them in parallel, you really need to have different recipes for different version of the tool, like we do, for example, for GEANT3 and GEANT4, which happily coexists.
- In case you cannot / do not want to run them in parallel, this becomes an environment configuration issue, so most likely the correct solution is to use modules or init.sh scripts to select the version you want.
