### ISSUE TITLE
aliBuild and aliDoctor disagree on autotools (on CentOS 7)

### ISSUE THREAD

**Issue by aphecetche** [alisw/alibuild#643]
on a CentOS7 machine, `aliBuild` and `aliDoctor` disagree on whether or not `autotools`should be taken from the system : 

```
[ dev ]{ alice-dev }~/alice/dev$ aliDoctor --defaults o2 autotools
SUCCESS: Package autotools will be picked up from the system.

==> The following packages will be picked up from the system:

    - autotools

    If this is not you want, you have to uninstall / unload them.

[ dev ]{ alice-dev }~/alice/dev$ aliBuild --defaults o2 build autotools
==> Packages will be built in the following order:
     - autotools@v1.6.3
Using cached build for defaults-release

==> Building autotools@v1.6.3
^C==> autotools is being built (use --debug for full output)...
```

(the defaults are the same, not like in #479 ;-) )

What I can note, if I add some debug output at the end of the `dockerStatusOutput` function (in `utilities.py`) : 

```
print("BEGIN TOTO cmd=%s\nEND TOTO"%cmd)
```

is that aliDoctor prints : 

```
BEGIN TOTO cmd=brew() { true; }; #export PATH=$PATH:$(brew --prefix gettext || true)/bin;
which autoconf && which m4 && which automake && which makeinfo && which aclocal && which pkg-config && which autopoint && which libtool;
if [ $? -ne 0 ]; then printf "One or more autotools packages are missing on your system.\n * On a RHEL-compatible system you probably need: autoconf automake texinfo gettext gettext-devel libtool\n * On an Ubuntu-like system you probably need: autoconf automake autopoint texinfo gettext libtool libtool-bin pkg-config\n * On macOS you need: brew install autoconf automake gettext pkg-config"; exit 1; fi
END TOTO
```

while aliBuild prints :  

```
BEGIN TOTO cmd=printf "#include <termcap.h>\n" | cc -xc - -c -o /dev/null
END TOTO
BEGIN TOTO cmd=type make
END TOTO
```

Incidentally, that's a problem because aliBuild is actually failing at compiling `autotools` afterwards ...

```
make[6]: Entering directory `/home/laurent/alice/dev/sw/BUILD/9c0e02463dd7a0f09a706cbe2e39d2a4f6bf0464/autotools/pkg-config-0.29.2/glib/glib'
  CC       libglib_2_0_la-gallocator.lo
  CC       libglib_2_0_la-gcache.lo
  CC       libglib_2_0_la-gcompletion.lo
  CC       libglib_2_0_la-grel.lo
  CC       libglib_2_0_la-gthread-deprecated.lo
  CC       libglib_2_0_la-garray.lo
  CC       libglib_2_0_la-gasyncqueue.lo
  CC       libglib_2_0_la-gatomic.lo
  CC       libglib_2_0_la-gbacktrace.lo
  CC       libglib_2_0_la-gbase64.lo
  CC       libglib_2_0_la-gbitlock.lo
  CC       libglib_2_0_la-gbookmarkfile.lo
  CC       libglib_2_0_la-gbytes.lo
  CC       libglib_2_0_la-gcharset.lo
  CC       libglib_2_0_la-gchecksum.lo
  CC       libglib_2_0_la-gconvert.lo
  CC       libglib_2_0_la-gdataset.lo
  CC       libglib_2_0_la-gdate.lo
  CC       libglib_2_0_la-gdatetime.lo
  CC       libglib_2_0_la-gdir.lo
  CC       libglib_2_0_la-genviron.lo
gconvert.c:61:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
 #error GNU libiconv not in use but included iconv.h is from libiconv
```

# versions used

```
[ dev ]{ alice-dev }~/alice/dev$ aliBuild version; pip --version; python --version
aliBuild version: 1.7.1 (slc7_x86-64)
pip 20.3.3 from /home/laurent/alice/dev/.venv/dev/lib/python3.8/site-packages/pip (python 3.8)
Python 3.8.6
 ```

**Comment by olantwin** [comment]
I seem to be running into the same issue on SLC9 for both GCC-toolchain and autotools, using the recipes from alisw/alidist master.

Just like @aphecetche, the defaults used for aliBuild and aliDoctor are the same.

Any ideas how to debug this or possible workarounds?

One observation:

* This seems to be architecture dependent: I cannot reproduce the issue on my own laptop with the same defaults and recipes.

**Comment by olantwin** [comment]
To answer my own question, it seems like this is the [intended behaviour](https://github.com/alisw/alidist/pull/1958#issuecomment-567430254). Would it be possible to add a warning to aliDoctor or aliBuild to explain this surprising behaviour?

**Comment by TimoWilken** [comment]
Hi @aphecetche, hi @olantwin, #824 (just merged) should fix this. I haven't made a release with this fix yet, since I might merge some more PRs in the next couple of days, but I'll make one later this week. Let me know if you still see any issues after this!

**Comment by olantwin** [comment]
Thanks, @TimoWilken . I can confirm that this now gives consistent information from both aliBuild and aliDoctor.

Is the preference for remote tarballs for scl7/9 documented somewhere? Apart from "not allowed or supported, by policy" statement, I haven't seen this information made explicit anywhere.

**Comment by TimoWilken** [comment]
Hi @olantwin, it is documented here: https://alisw.github.io/alibuild/user.html (under "Using precompiled packages") and here: <https://alice-doc.github.io/alice-analysis-tutorial/building/build.html#%F0%9F%9B%A0-build-the-packages>.

It's not very well documented in those places so far, so I've submitted some PRs to improve it and specify what platforms this applies to.

**Comment by olantwin** [comment]
Thanks a lot!

Might be interesting to compare notes sometime on how different experiments use aliBuild. We(SND@LHC and SHiP) have never tried using the precompiled packages (which is probably why I never looked at that part of the documentation), but use a precompiled stack from CVMFS with only some packages then built locally on top/in addition to this stack.
