### ISSUE TITLE
O2 building very slowly after updating to aliBuild 1.7.1

### ISSUE THREAD

**Issue by jbarrella** [alisw/alibuild#649]
I hadn't built O2 since November. I recently rebuilt it after updating aliBuild to 1.7.1 and updating my `alidist` checkout. I find the build/rebuild process to have slowed down considerably when using cached packages. I have attached a screenshot of the behavior below. Instead of pulling the latest version of each package, aliBuild seems to process several previous versions as well. For `ALICE-grid-Utils` there are only a few versions, but in other cases there are many. I'm not sure if this is intentional, but it seems to be slowing the build down a lot and I don't recall it ever doing this in the past. Any ideas as to what would be causing this?

Please let me know if this issue should be posted elsewhere like the `alidist` repo.

I am running CentOS 7 inside WSL. Thanks for any help.

![Image Pasted at 2021-2-9 09-18](https://user-images.githubusercontent.com/32719308/107358545-31748000-6adc-11eb-8587-4c62e916b074.png)

EDIT: Updated to 1.7.2, but do not notice an improvement.

**Comment by jbarrella** [comment]
I should point out here that I am part of the South African ALICE contingent. I think this issue is not as severe when building from CERN, Germany, and surrounding EU regions where the latency is considerably lower. However, for us, the effect is quite severe. Thanks.

**Comment by ktf** [comment]
Can you check if 1.7.3 improved the situation?

**Comment by jbarrella** [comment]
Hi. I did a build with 1.7.3 this week and did not notice a significant improvement.

**Comment by ktf** [comment]
Could you do a bit more profiling on what actually takes time? You should be able to do so with something like:

```bash
python3 -m cProfile `which aliBuild` ... 
```

it should print out some stats which you can paste here.

**Comment by jbarrella** [comment]
Sure, thanks. Does this help?

[profile.txt](https://github.com/alisw/alibuild/files/6136399/profile.txt)

**Comment by ktf** [comment]
Sorry, can you use `-s cumtime` to sort it by cumulative time?

**Comment by jbarrella** [comment]
[profile_sort_cumulative.txt](https://github.com/alisw/alibuild/files/6147299/profile_sort_cumulative.txt)

No problem. Thanks for the assistance.

**Comment by ktf** [comment]
You need to actually build something with it enabled. The report you have measured less than one second...

**Comment by jbarrella** [comment]
Ah okay, I'll try to build at some point then between the times that we have no electricity and get back to you.

**Comment by jbarrella** [comment]
Hi, I built over the weekend with `python3 -m cProfile -s cumtime 'aliBuild build O2 --defaults o2 -j 6'`. Unfortunately, this did not work as hoped. The build was successful, but I guess my syntax for the profiling was off. Could you give me an example of the proper syntax please?

**Comment by ktf** [comment]
For the record, we have identified and committed a fix to the slow access to S3. Can you try using the head of alibuild?

**Comment by jbarrella** [comment]
Hi @ktf,

How do I go about using HEAD? I tried to clone the repo and install it, but didn't seem to work

**Comment by ktf** [comment]
This should have been improved in 1.8.0. Can you try with that? `pip install alibuild==1.8.0` should allow you to update.

**Comment by jbarrella** [comment]
Issue is resolved in 1.8.0. Many thanks for the support
