### ISSUE TITLE
aliBuild not picking up changes to files

### ISSUE THREAD

**Issue by aimeric-landou** [alisw/alibuild#694]
Hi,
been making some changes to analysis tasks on a local installation of O2. Running `aliBuild build O2 --defaults o2` sometimes does not seem to see the changes (I tested it by removing a ; where there should be one, or adding a random suite of letters between lines), and states `Development package O2 does not need rebuild`. 
Is that an expected behaviour? 

![image](https://user-images.githubusercontent.com/46970521/119022892-07fba800-b999-11eb-9760-f1df17b5b513.png)

It does seem to pickup changes were made if I create a new task and edit a CMakeLists.txt file, but further alteration to this new task are met with the same behaviour as above

**Comment by ktf** [comment]
AliBuild can only automatically rebuild what is known to git. Is such a file committed?

**Comment by aimeric-landou** [comment]
That explains that. No it was not yet.
