### ISSUE TITLE
Partial clone breaks offline usage with `clang.sh`

### ISSUE THREAD

**Issue by dennisklein** [alisw/alibuild#695]
90650cd19b8ced4a930080cd05e5e425f649b1ee appears to break offline usage and causes excessive resource usage on `-u`:

In the following comparison
* `<llvm>` is `https://github.com/llvm/llvm-project`,
* `<tag>` is `llvmorg-11.1.0`, and
* a laptop with a local SSD and 16GB RAM is used:

| | | `git` | **full clone** | **partial clone** `--filter=blob:none` |
| --- | --- | --- | --- | --- |
| 1 | MIRROR creation | `clone --bare <llvm>` | `1.52 GiB, 12.04 MiB/s, wall time: 3:58.01` | `412.84 MiB, 12.03 MiB/s, wall time: 0:49.55` |
| 2a | SOURCE creation | `clone -n --reference <MIRROR> <llvm>` | `no network traffic, wall time: 0:00.77` | `no network traffic, wall time: 0:00.55` |
| 2b | SOURCE creation | `checkout -f <tag>` | `no network traffic, wall time: 0:05.02` | `127.42 MiB, 9.89 MiB/s, wall time: 0:52.72` |
| 3a | MIRROR `-u` | `fetch -f --tags <llvm>`| `wall time: 0:00.54, max RSS: 63828 kbytes` | `wall time: 2:17.47, max RSS: 8197848 kbytes` |
| 3b | MIRROR `-u` | `fetch -f <llvm> +refs/heads/*:refs/heads/*`| `wall time: 0:00.37, max RSS: 64748 kbytes` | `wall time: 4:29.54, max RSS: 8246948 kbytes` |

**aliBuild**: 1.8.4
**OS**: Fedora 34
**Git**: 2.31.1

Have not checked other packages or other Git versions. From what I have seen it looks to me like some git bug with partial clones or maybe intended behaviour with unlucky `--filter` value?!

**Comment by TimoWilken** [comment]
As I understand it, `--filter=blob:none` explicitly doesn't fetch file contents, saving bandwidth on the initial clone. On checkout, those file contents need to be fetched, though, hence the network traffic in 2b.

If we only need a specific commit to build, perhaps it would be better to use something like `git clone -b <commit> --depth 1 <url>` instead? As far as I can tell, we don't use the commit history, right? @ktf?

I can't reproduce the long runtimes of the `git fetch` commands locally (I manually cloned the repos, but I can't see anything obvious that aliBuild is doing differently; git 2.31.1 also).

**Comment by dennisklein** [comment]
> I can't reproduce the long runtimes of the git fetch commands locally (I manually cloned the repos, but I can't see anything obvious that aliBuild is doing differently; git 2.31.1 also).

You are right! I re-checked and now it is fast for me as well (both with aliBuild and with manual git command sequence). I guess, it must have been a temporary issue - possibly with my internet connection or due to some service degradation (on weekends)? (I frequently see very slow connections to the geant4 cern gitlab on weekends, too). Sry for the noise here!

> we only need a specific commit to build, perhaps it would be better to use something like `git clone -b <commit> --depth 1 <url>` instead? As far as I can tell, we don't use the commit history, right?

Hmm, having thought about it a bit more, I would prefer a simple switch to disable partial clones (does it already exist?) - default behavior can stay at it is - next time I find some time, I can propose a PR for such a switch, if you want, it is not urgent. That said, I don't think shallow clones (`--depth 1`) are a good idea to save space/traffic for the MIRROR clones (I know some repos where the build systems queries the source tree via `git` - that is actually one quality of aliBuild I value very much; that it has first class git integration in contrary to other package managers - I would love to not see this gone ;) ).

**Comment by ktf** [comment]
Indeed, `--filter blob:none` is actually what we want: the whole history, without the full cost of the history, unless explicitly requested. Maybe we should check if there is something which triggers a big fetch. It could also depend of the way the blobs are stored (you always get a pack, not a single blob, so if llvm uses large packs, you might end up downloading more than you wanted).
