### ISSUE TITLE
Error during the installation of O2

### ISSUE THREAD

**Issue by MuradBadshah** [alisw/alibuild#705]
I am installing O2 in my ubuntu 20.10 but get the following error, plz some help me, thanks in advance.

=> You have packages in development mode.
    This means their source code can be freely modified under:
    
      /home/muradbadshah/alice/<package_name>
    
    aliBuild does not automatically update such packages to avoid work loss.
    In most cases this is achieved by doing in the package source directory:
    
      git pull --rebase
    
Using cached build for defaults-release
Using cached build for lhapdf
Using cached build for OpenSSL
Using cached build for GMP
Using cached build for UUID
Using cached build for ninja
Using cached build for Python-modules-list
Using cached build for json-c
Using cached build for libtirpc
Using cached build for Alice-GRID-Utils
Using cached build for ofi
Using cached build for O2-customization
Using cached build for alibuild-recipe-tools
Using cached build for ApMon-CPP
Using cached build for AliEn-CAs
Using cached build for MPFR
Using cached build for ZeroMQ
Using cached build for CMake
Using cached build for AliEn-Runtime
Using cached build for curl
Using cached build for Clang
Using cached build for Vc
Using cached build for libwebsockets
Using cached build for ms_gsl
Using cached build for re2
Using cached build for protobuf
Using cached build for GEANT4
Using cached build for lz4
Using cached build for RapidJSON
Using cached build for fmt
Using cached build for pythia6
Using cached build for googlebenchmark
Using cached build for capstone
Using cached build for FFTW3
Using cached build for double-conversion
Using cached build for flatbuffers
Using cached build for libjalienO2
Using cached build for FreeType
Using cached build for FairLogger
Using cached build for DebugGUI
Using cached build for Python-modules
Using cached build for XRootD
Using cached build for boost
Using cached build for xjalienfs
Using cached build for yaml-cpp
Using cached build for pythia
Using cached build for Common-O2
Using cached build for asiofi
Using cached build for arrow
Using cached build for DDS
Using cached build for Ppconsul
Using cached build for cgal
Using cached build for libInfoLogger
Using cached build for generators

==> Building ROOT@v6-20-08-alice1
==> ROOT is being built (use --debug for full output): failed    
ERROR: Error while executing /home/muradbadshah/alice/sw/SPECS/ubuntu2010_x86-64/ROOT/v6-20-08-alice1-local1/build.sh on `Latitude-E7470'.
ERROR: Log can be found in /home/muradbadshah/alice/sw/BUILD/ROOT-latest/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is /home/muradbadshah/alice/sw/BUILD/ROOT-latest/ROOT.

**Comment by TimoWilken** [comment]
Hi @MuradBadshah, please post the `/home/muradbadshah/alice/sw/BUILD/ROOT-latest/log` file.

(If you paste it into a comment, please surround it with a line of three backticks (\`\`\`) before the first line and after the last, to make it readable.)

In future, a better place for these questions is <https://alice-talk.web.cern.ch/>.

**Comment by MuradBadshah** [comment]
'''++ unset ROOTSYS
++ COMPILER_CC=cc
++ COMPILER_CXX=c++
++ COMPILER_LD=c++
++ case $PKGVERSION in
++ ENABLE_VMC=1
++ [[ -fPIC -O2 -std=c++17 == *\-\s\t\d\=\c\+\+\1\1* ]]
++ true
++ [[ -fPIC -O2 -std=c++17 == *\-\s\t\d\=\c\+\+\1\4* ]]
++ true
++ [[ -fPIC -O2 -std=c++17 == *\-\s\t\d\=\c\+\+\1\7* ]]
++ CMAKE_CXX_STANDARD=17
++ unset CXXFLAGS
++ unset CFLAGS
++ unset LDFLAGS
++ SONAME=so
++ case $ARCHITECTURE in
++ [[ -n v2-19-le ]]
++ OPENSSL_ROOT=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1
++ LIBXML2_ROOT=
++ [[ -n '' ]]
++ [[ -d /home/muradbadshah/alice/sw/SOURCES/ROOT/v6-20-08-alice1/v6-20-08-alice1/interpreter/llvm ]]
++ ROOT_PYTHON_FLAGS='-Dpyroot=ON -Dpyroot_legacy=ON'
++ ROOT_PYTHON_FEATURES=pyroot
++ ROOT_HAS_PYTHON=1
+++ python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_config_var("exec_prefix"));'
++ PYTHON_EXECUTABLE=/usr/bin/python3
++ unset DYLD_LIBRARY_PATH
++ cmake /home/muradbadshah/alice/sw/SOURCES/ROOT/v6-20-08-alice1/v6-20-08-alice1 -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_INSTALL_PREFIX=/home/muradbadshah/alice/sw/INSTALLROOT/6c95bd592a48d3c4ccb9dc8b50a3677d231fb329/ubuntu2010_x86-64/ROOT/v6-20-08-alice1-local1 -Dalien=OFF -DMONALISA_DIR=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1 -DXROOTD_ROOT_DIR=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/XRootD/v4.11.1-local1 -DCMAKE_CXX_STANDARD=17 -Dfreetype=ON -Dbuiltin_freetype=OFF -Dpcre=OFF -Dbuiltin_pcre=ON -Dsqlite=OFF -Dpyroot=ON -Dpyroot_legacy=ON -Darrow=ON -DARROW_HOME=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/arrow/v1.0.0-local1 -DCMAKE_CXX_COMPILER=c++ -DCMAKE_C_COMPILER=cc -Dfortran=OFF -DCMAKE_LINKER=c++ -DOPENSSL_ROOT=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1 -DOPENSSL_INCLUDE_DIR=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1/include -Dpgsql=OFF -Dminuit2=ON -Dpythia6_nolink=ON -Droofit=ON -Dhttp=ON -Droot7=OFF -Dsoversion=ON -Dshadowpw=OFF -Dvdt=ON -Dbuiltin_vdt=ON -Dmonalisa=ON -Dkrb5=OFF -Dgviz=OFF -Dbuiltin_davix=OFF -Dbuiltin_afterimage=ON -Dvmc=ON -Ddavix=OFF -DPYTHON_PREFER_VERSION=3 -DPYTHON_EXECUTABLE=/usr/bin/python3 '-DCMAKE_PREFIX_PATH=/home/muradbadshah/alice/sw/ubuntu2010_x86-64/FreeType/v2.10.1-local1;;;/home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1;;/home/muradbadshah/alice/sw/ubuntu2010_x86-64/Python-modules/1.0-local1;;'
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Detected ROOT_VERSION 6.20.08
-- Looking for python
-- Preferring Python version 3
-- Found Python3: /usr/bin/python3 (found version "3.8.10") found components: Interpreter 
-- ROOT default compression algorithm: zlib
CMake Deprecation Warning at cmake/modules/RootBuildOptions.cmake:391 (message):
  >>> Option 'vmc' is deprecated and will be removed in the next release of
  ROOT.  Please contact root-dev@cern.ch should you still need it.
Call Stack (most recent call first):
  CMakeLists.txt:122 (include)


-- Found GCC. Major version 10, minor version 3
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found a 64bit system
-- Found GNU compiler collection
-- Performing Test GLIBCXX_USE_CXX11_ABI
-- Performing Test GLIBCXX_USE_CXX11_ABI - Success
-- ROOT Platform: linux
-- ROOT Architecture: linuxx8664gcc
-- Build Type: RELWITHDEBINFO (flags = '-O2 -g -DNDEBUG')
-- Compiler Flags: -O2 -g -DNDEBUG  -std=c++17 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread
-- Looking for ZLib
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Looking for Freetype
-- Found Freetype: /home/muradbadshah/alice/sw/ubuntu2010_x86-64/FreeType/v2.10.1-local1/lib/libfreetype.so (found version "2.10.1") 
-- Looking for LZMA
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/lib/x86_64-linux-gnu/liblzma.so (found version "5.2.4") 
-- Looking for ZSTD
-- Could NOT find ZSTD (missing: ZSTD_INCLUDE_DIR ZSTD_VERSION) 
-- ZSTD not found. Switching on builtin_zstd option
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11 - Success
-- Performing Test C_FLAG_STD_C99
-- Performing Test C_FLAG_STD_C99 - Success
-- Performing Test C_FLAG_WALL
-- Performing Test C_FLAG_WALL - Success
-- Performing Test CXX_FLAG_WALL
-- Performing Test CXX_FLAG_WALL - Success
-- Performing Test C_FLAG_WEXTRA
-- Performing Test C_FLAG_WEXTRA - Success
-- Performing Test CXX_FLAG_WEXTRA
-- Performing Test CXX_FLAG_WEXTRA - Success
-- Performing Test C_FLAG_WUNDEF
-- Performing Test C_FLAG_WUNDEF - Success
-- Performing Test CXX_FLAG_WUNDEF
-- Performing Test CXX_FLAG_WUNDEF - Success
-- Performing Test C_FLAG_WSHADOW
-- Performing Test C_FLAG_WSHADOW - Success
-- Performing Test CXX_FLAG_WSHADOW
-- Performing Test CXX_FLAG_WSHADOW - Success
-- Performing Test C_FLAG_WCAST_ALIGN
-- Performing Test C_FLAG_WCAST_ALIGN - Success
-- Performing Test CXX_FLAG_WCAST_ALIGN
-- Performing Test CXX_FLAG_WCAST_ALIGN - Success
-- Performing Test C_FLAG_WCAST_QUAL
-- Performing Test C_FLAG_WCAST_QUAL - Success
-- Performing Test CXX_FLAG_WCAST_QUAL
-- Performing Test CXX_FLAG_WCAST_QUAL - Success
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
-- Looking for xxHash
-- Could NOT find xxHash (missing: xxHash_INCLUDE_DIR) 
-- xxHash not found. Switching on builtin_xxhash option
-- Looking for LZ4
CMake Warning (dev) at cmake/modules/SearchInstalledSoftware.cmake:15 (_find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable LZ4_ROOT is set to:

    /home/muradbadshah/alice/sw/ubuntu2010_x86-64/lz4/v1.9.3-local1

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/modules/SearchInstalledSoftware.cmake:284 (find_package)
  CMakeLists.txt:169 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LZ4 (missing: LZ4_INCLUDE_DIR) 
-- LZ4 not found. Switching on builtin_lz4 option
-- Looking for X11
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- X11_INCLUDE_DIR: /usr/include;/home/muradbadshah/products/root/include
-- X11_LIBRARIES: /usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- X11_Xpm_INCLUDE_PATH: /usr/include
-- X11_Xpm_LIB: /usr/lib/x86_64-linux-gnu/libXpm.so
-- X11_Xft_INCLUDE_PATH: /usr/include
-- X11_Xft_LIB: /usr/lib/x86_64-linux-gnu/libXft.so
-- X11_Xext_INCLUDE_PATH: /usr/include
-- X11_Xext_LIB: /usr/lib/x86_64-linux-gnu/libXext.so
-- Could NOT find GIF (missing: GIF_LIBRARY GIF_INCLUDE_DIR) 
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR) 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
-- Building AfterImage library included in ROOT itself
-- Looking for GSL
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found GSL: /usr/include (found suitable version "2.6", minimum required is "1.10") 
-- Looking for OpenGL
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Looking for GLEW
-- Found GLEW: /usr/include (found version "2.1.0") 
-- Looking for gl2ps
CMake Warning (dev) at /home/muradbadshah/alice/sw/ubuntu2010_x86-64/CMake/v3.19.2-local1/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (GL2PS) does
  not match the name of the calling package (gl2ps).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/Findgl2ps.cmake:27 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/modules/SearchInstalledSoftware.cmake:15 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:546 (find_Package)
  CMakeLists.txt:169 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find GL2PS (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR) 
-- gl2ps not found. Switching on builtin_gl2ps option
-- Looking for LibXml2
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.10") 
-- Found OpenSSL: /home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1/lib/libcrypto.so (found version "1.0.2o")  
-- Looking for MySQL
CMake Warning (dev) at /home/muradbadshah/alice/sw/ubuntu2010_x86-64/CMake/v3.19.2-local1/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (MYSQL) does
  not match the name of the calling package (MySQL).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindMySQL.cmake:65 (find_package_handle_standard_args)
  cmake/modules/SearchInstalledSoftware.cmake:15 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:612 (find_package)
  CMakeLists.txt:169 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found MYSQL: /usr/include/mysql  
-- Looking for Oracle
-- Oracle not found.
-- Oracle: You can specify includes: -DORACLE_PATH_INCLUDES=/usr/include/oracle/10.2.0.3/client
--    currently found includes: 
-- Oracle: You can specify libs: -DORACLE_PATH_LIB=/usr/lib/oracle/10.2.0.3/client/lib
--    currently found libs: ORACLE_LIBRARY_OCCI-NOTFOUND;ORACLE_LIBRARY_CLNTSH-NOTFOUND;ORACLE_LIBRARY_LNNZ-NOTFOUND
-- Oracle not found. Switching off oracle option
-- Looking for Pythia6
-- Looking for Pythia8
-- Could NOT find Pythia8 (missing: PYTHIA8_INCLUDE_DIR PYTHIA8_LIBRARY) 
-- Pythia8 not found. Switching off pythia8 option
-- Looking for FFTW3
-- Found fftw3 includes at /usr/include
-- Found fftw3 library at /usr/lib/x86_64-linux-gnu/libfftw3.so
-- Looking for CFITSIO
-- Found CFITSIO: /usr/lib/x86_64-linux-gnu/libcfitsio.so (found version "3.49") 
-- Found Monalisa: /home/muradbadshah/alice/sw/ubuntu2010_x86-64/AliEn-Runtime/v2-19-le-local1/lib/libapmoncpp.so  
-- Looking for XROOTD
CMake Warning (dev) at cmake/modules/SearchInstalledSoftware.cmake:15 (_find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable XROOTD_ROOT is set to:

    /home/muradbadshah/alice/sw/ubuntu2010_x86-64/XRootD/v4.11.1-local1

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/modules/SearchInstalledSoftware.cmake:852 (find_package)
  CMakeLists.txt:169 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Xrootd version num: 4.12.8 (setting -DROOTXRDVERS=400120008)
--              libXrdMain not found: xproofd will be a wrapper around xrootd
--              include_dirs: /home/muradbadshah/products/root/include;/home/muradbadshah/products/root/include/private
--              libraries: /home/muradbadshah/products/root/lib/libXrdUtils.so;/home/muradbadshah/products/root/lib/libXrdClient.so;/home/muradbadshah/products/root/lib/libXrdCl.so
CMake Warning (dev) at /home/muradbadshah/alice/sw/ubuntu2010_x86-64/CMake/v3.19.2-local1/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (Arrow).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/muradbadshah/alice/sw/ubuntu2010_x86-64/CMake/v3.19.2-local1/share/cmake-3.19/Modules/FindPkgConfig.cmake:67 (find_package_handle_standard_args)
  cmake/modules/FindArrow.cmake:27 (include)
  cmake/modules/SearchInstalledSoftware.cmake:15 (_find_package)
  cmake/modules/SearchInstalledSoftware.cmake:950 (find_package)
  CMakeLists.txt:169 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found the Arrow core library: /home/muradbadshah/alice/sw/ubuntu2010_x86-64/arrow/v1.0.0-local1/lib/libarrow.so
-- Found the Arrow Python library: ARROW_PYTHON_LIB_PATH-NOTFOUND
-- Could NOT find GFAL (missing: GFAL_INCLUDE_DIR SRM_IFCE_INCLUDE_DIR GFAL_LIBRARY) 
-- GFAL library not found. Set variable GFAL_DIR to point to your gfal installation
                      and the variable SRM_IFCE_DIR to the srm_ifce installation
-- For the time being switching OFF 'gfal' option
-- Found FTGL: /usr/include  
-- Looking for TBB
-- Found TBB: /usr (found suitable version "2020.3", minimum required is "2018")  
-- Cannot select cudnn without selecting cuda or tmva-gpu. Option is ignored
-- Looking for BLAS for optional parts of TMVA
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Using GSL CBLAS for optional parts of TMVA
-- Performing Test ROOT_HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test ROOT_HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Building LLVM in 'Release' mode.
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc'''

**Comment by TimoWilken** [comment]
Thanks. I can't see an error that would make the build fail in there -- there are a bunch of legitimate warnings from CMake, but it seems to be fine (for now) falling back to system packages. Could you please re-run the original aliBuild command, but with the `--debug` flag added, and post the output?

**Comment by TimoWilken** [comment]
Sorry, I don't know how to solve this. The only suggestion I can give is to try running aliBuild with the `--no-system` option, in case it's using your system cmake and that's causing the warnings, which might lead to the errors later on.

You'll probably find better help at <https://alice-talk.web.cern.ch/>.

**Comment by MuradBadshah** [comment]
I managed it by using  ```sudo aliBuild build O2 --defaults o2``` instead of ``` aliBuild build O2 --defaults o2  ```

**Comment by MuradBadshah** [comment]
aliBuild build O2 --defaults o2

**Comment by MuradBadshah** [comment]
I managed it by using sudo aliBuild build O2 --defaults o2 instead of aliBuild
build O2 --defaults o2
