### ISSUE TITLE
Alibuild fail building AliRoot on alidock. (Error while building AliRoot@master)

### ISSUE THREAD

**Issue by boonying04** [alisw/alibuild#706]
Hi,
I got the problem while building AliRoot on my docker (alidock).
I had clone alidist via "aliBuild init AliRoot@master"
and then I start to build AliRoot by "aliBuild build AliRoot", the process seems to be fine until it building AliRoot@master. I got the error message about CMake Error, the error message from debug output is below here.

>   DEBUG:AliRoot:AliRoot:0: CMake Error:
>   DEBUG:AliRoot:AliRoot:0:   Running
>   DEBUG:AliRoot:AliRoot:0:
>   DEBUG:AliRoot:AliRoot:0:    '/usr/local/bin/ninja' '-C' '/persist/sw/BUILD/6b39f7c6669dcde3d6d8908094bb426f09a6ad45/AliRoot' '-t' 'recompact'
>   DEBUG:AliRoot:AliRoot:0:
>   DEBUG:AliRoot:AliRoot:0:   failed with:
>   DEBUG:AliRoot:AliRoot:0:
>   DEBUG:AliRoot:AliRoot:0:    ninja: warning: phony target 'STEER/STEERBase/libSTEERBase.rootmap' names itself as an input; ignoring [-w phonycycle=warn]
>   DEBUG:AliRoot:AliRoot:0:
>   DEBUG:AliRoot:AliRoot:0:   ninja: error: build.ninja:1437: multiple rules generate
>   DEBUG:AliRoot:AliRoot:0:   STEER/STEERBase/libSTEERBase.rootmap [-w dupbuild=err]
>   DEBUG:AliRoot:AliRoot:0:
>   DEBUG:AliRoot:AliRoot:0: CMake Generate step failed.  Build files cannot be regenerated correctly.
>   ERROR:AliRoot:AliRoot:0: Error while executing /persist/sw/SPECS/slc7_x86-64/AliRoot/master-local1/build.sh on `alidock-501'.
>   ERROR:AliRoot:AliRoot:0: Log can be found in /persist/sw/BUILD/AliRoot-latest/log
>   ERROR:AliRoot:AliRoot:0: Please upload it to CERNBox/Dropbox if you intend to request support.
>   ERROR:AliRoot:AliRoot:0: Build directory is /persist/sw/BUILD/AliRoot-latest/AliRoot. 

Any advice would be appreciated.
Thank you for your support.

**Comment by TimoWilken** [comment]
Hi @boonying04. Sorry, this is not the right place to ask for help with build errors. Please post in https://alice-talk.web.cern.ch/ instead.

**Comment by boonying04** [comment]
Sorry, about this and thank you for your response.
