### ISSUE TITLE
CONFIG_DIR env variable missing during build

### ISSUE THREAD

**Issue by jan-busa** [alisw/alibuild#761]
In the reference manual (https://alisw.github.io/alibuild/reference.html#the-body) is written that during build variable ```CONFIG_DIR``` containing path to the recipes directory is available but this is not so. Looking at the alibuild sources I can see, that only place containing CONFIG_DIR is a documentation. Therefore I would like to ask how can I obtain the path to the recipes during the build.

Also I would like to propose to consider changing of the name of this variable to something like RECIPES_DIR. This better reflects the purpose of the variable and will not conflict with CONFIG_DIR variable used by FairRoot.

**Comment by TimoWilken** [comment]
Hi @jan-busa, may I ask why you need to parse the alidist recipes during the build? The way alibuild parses can be quite complex, so perhaps there is an easier way to achieve what you need.

Indeed `CONFIG_DIR` is not set currently -- perhaps it used to be and wasn't removed from the documentation.

While alidist would be accessible when building on the host machine, we currently don't mount the alidist directory at all when building inside a container (using `--docker`).

**Comment by jan-busa** [comment]
Hello, I'm sorry for such late reply. I'm using fork of alidist and I wanted to keep patches together with recipes so that in case of software version change I could patch new sources "automagically'. But with time and complexity of patches I now understand that your approach of having patched forks of needed software is more consistent.
