### ISSUE TITLE
!#/usr/bin/env python does not work on most/a lot of systems

### ISSUE THREAD

**Issue by olantwin** [alisw/alibuild#843]
When cloning aliBuild instead of installing using pip (in our case to put a copy on CVMFS), the shebang `!#/usr/bin/env python` will not work on most systems (e.g. SLC9, macOS 12, recent Fedora and Ubuntu (?)).

Now that python2 is a matter of the past, could we switch this shebang to python3?

**Comment by ktf** [comment]
You mean like in https://github.com/alisw/alibuild/pull/844?

**Comment by ktf** [comment]
For the record, I have just released v1.17.2 with the above mentioned fix and a bugfix for the build dependencies. Feel free to try it out and provide feedback, if you want.

**Comment by olantwin** [comment]
Thanks, I'm testing it now, I'll let you know if I have any feedback!
