### ISSUE TITLE
"SCM not found" due to git repository ownership checks

### ISSUE THREAD

**Issue by olantwin** [alisw/alibuild#845]
Because of a [git safety feature](https://github.blog/2022-04-18-highlights-from-git-2-36/#stricter-repository-ownership-checks), we frequently run into the above error from alibuild, as we distribute our fork of alidist on CVMFS.

The git error is quite helpful, and instructs the user how to add a security exception for $ALIDIST, but it is not passed on when the SCMError is raised in https://github.com/alisw/alibuild/blob/master/alibuild_helpers/build.py#L488 .

While I'm not sure whether there's a way to avoid the underlying issue, forwarding the SCM error messages to stdout/err in generally would help troubleshoot this issue (and potential other issues).

I can try to implement this, but unfortunately can't offer an ETA.

CC @siilieva, as this also affects SND@LHC

**Comment by ktf** [comment]
Do you have an example of what is the actual git command which fails? Or if you prefer, can you point me to your CVMFS repository?

**Comment by olantwin** [comment]
> Do you have an example of what is the actual git command which fails? Or if you prefer, can you point me to your CVMFS repository?

AFAIK it's `git rev-parse HEAD`, but generally it should be the first git command aliBuild attempts to perform on the shipdist repo.

For reference, `/cvmfs/ship.cern.ch/24.05.1/shipdist`

**Comment by olantwin** [comment]
> We avoid printing verbatim error messages from git as a security measure, since they could potentially expose details of the build infrastructure we do not want to expose (e.g. the environment variables at the moment of the git command).

Fair enough, that's a constraint I had not thought about.

> Maybe a solution would be to check if the user owns the target repository

For now I will work around this issue by adding a warning to the SHiP setup script, so that users are prompted to add the exception. This doesn't feel like an ideal permanent solution though.

> (or maybe we could simply whitelist /cvmfs on alibuild side).

Since the whitelist would need to be for git, I'm not sure how a whitelist in aliBuild could solve this.

> That said, why not using `git clone --filter=blob:none` or similar?

I'm not sure I understand what you're suggesting here.

**Comment by ktf** [comment]
> For now I will work around this issue by adding a warning to the SHiP setup script, so that users are prompted to add the exception. This doesn't feel like an ideal permanent solution though.
> (or maybe we could simply whitelist /cvmfs on alibuild side).

What I can do is to add a check on the SCM class side and prepend the correct whitelisting command (it must be something like `git config --local`, IIUC) if needed.

**Comment by olantwin** [comment]
> > (or maybe we could simply whitelist /cvmfs on alibuild side).
> 
> What I can do is to add a check on the SCM class side and prepend the correct whitelisting command (it must be something like `git config --local`, IIUC) if needed.

That should work! The command would be 

```
git config --global --add safe.directory /path/to/dist
```

To not introduce a security issue on the alibuild side though, this probably should not happen silently, but at least require a `y/n` prompt.

**Comment by ktf** [comment]
Can you point me to  the actual script that you run? I am unable to reproduce with a simply git clone.

**Comment by olantwin** [comment]
For me this command is sufficient to reproduce (`--force-unknown-architecture` unrelated, as I'm on my laptop right now):

```
aliBuild build -c /cvmfs/ship.cern.ch/24.05.1/shipdist/ --default release FairShip --force-unknown-architecture
```

With `shipdist` being owned by the cvmfs user and group.
```
drwxr-xr-x  2 cvmfs cvmfs    26 May 22 08:42 shipdist/
```

**Comment by ktf** [comment]
Can you check if https://github.com/alisw/alibuild/pull/846 solves your issue?

**Comment by ktf** [comment]
@olantwin in case you did not see the above.

**Comment by olantwin** [comment]
@ktf Sorry for the late reply, in the US for a conf.

I can confirm that the approach should work:

```bash
GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=safe.directory GIT_CONFIG_VALUE_0=$PWD git rev-parse HEAD .
```
This returns the expected result instead of the git warning message.

*However*, when using your branch I still get the `SCM not found` error. I'm trying to understand why now...

**Comment by ktf** [comment]
I suspect the issue is indeed if you have a relative path. Updated as you suggest above.

**Comment by olantwin** [comment]
I can confirm that #846 fixes the issue for me.

I didn't realise that directories could be made safe for a single command!

**Comment by ktf** [comment]
Frankly speaking, it's the first time I do the trick as well.. ;-)
