### ISSUE TITLE
modulecmd in docker containers

### ISSUE THREAD

**Issue by qgp** [alisw/alibuild#87]
Hi,

could you add modulecmd on the docker images to allow using aliModules without cvmfs?

Cheers,
   Jochen

**Comment by dberzano** [comment]
Hello @qgp, there is no reason for it to happen. We would have to bring TCL. The package `environment-modules` is widely available so install it from your distribution and we don't want to increase exponentially the number of dependencies.

**Comment by qgp** [comment]
Hi @dberzano, sorry I don't understand this. If I want to test that a package works properly in the target environment I have to do it in the container, not on my native OS. And in the container it doesn't help me that I have modules installed on the host OS (I have, of course).

Cheers,
   Jochen

**Comment by dberzano** [comment]
You are right: can you open an issue, or a Pull Request, on alisw/docks in a way that we supply environment-modules within a container?

**Comment by qgp** [comment]
Sure, I'll file a pull request there.
