### ISSUE TITLE
wrong modulefiles when building package in devel mode

### ISSUE THREAD

**Issue by qgp** [alisw/alibuild#99]
When building a package with the devel option, I end up with a wrong modulefile. The problem is that the version is not properly replaced but contains something like:
0-@@PKGREVISION@0af2c75190cad609e350ddd415ed9dca0487db1f@@

What's interesting is that the version is correct in the modulefile for another package also using the devel mode but which was built as a dependence.

**Comment by qgp** [comment]
@dberzano: one more problem, the incremental build does not install the module file.

**Comment by ktf** [comment]
Should be fixed by  #153.
